wave-harmonic/crest

- src/unity/Assets/Crest-Examples/Scripts/OceanDebugGUI.cs
- src/unity/Assets/Crest-Examples/WaveSpectra/WavesModerateSmooth.asset
- src/unity/Assets/Crest/Scripts/Helpers/CreateAssignRenderTexture.cs
- src/unity/Assets/Crest/Scripts/LodData/LodData.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataAnimatedWaves.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataDynamicWaves.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataFoam.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataSeaFloorDepth.cs
- src/unity/Assets/Crest/Scripts/OceanRenderer.cs
- src/unity/Assets/Crest/Scripts/OceanScheduler.cs
- src/unity/Assets/Crest/Scripts/OceanScheduler.cs.meta
An attempt to make scheduling / dependencies more explicit. Scheduling can be overridden which may help with scripted render pipelines which require specific hooks.
@moosichu if you have feedback let me know.
> Ocean scheduler - consolidate scheduling in one place

- src/unity/Assets/Crest-Examples/Scripts/OceanDebugGUI.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataSeaFloorDepth.cs
- src/unity/Assets/Crest/Scripts/OceanDepthCache.cs
- src/unity/Assets/Crest/Scripts/RenderOceanDepth.cs
Hi @dizzy2003 ,
Would these changes resolve issues #65 and #66 ?
Thanks for the suggestion!
> Refactor ocean depth registration

- src/unity/Assets/Crest/Scripts/LodData/LodDataShadow.cs
- src/unity/Assets/Crest/Scripts/LodData/Settings/SimSettingsShadow.cs
> Add the ability for lights to be changed in LodDataShadow at runtime

- src/unity/Assets/Crest-Examples/BoatDev/Scripts/FeedVelocityToExtrude.cs
- src/unity/Assets/Crest-Examples/Scripts/Simulation/RippleGenerator.cs
- src/unity/Assets/Crest/Scripts/OceanRenderer.cs
- src/unity/Assets/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- src/unity/Assets/Crest/Scripts/Time.meta
- src/unity/Assets/Crest/Scripts/Time/TimeProviderBase.cs
- src/unity/Assets/Crest/Scripts/Time/TimeProviderBase.cs.meta
- src/unity/Assets/Crest/Scripts/Time/TimeProviderCustom.cs
- src/unity/Assets/Crest/Scripts/Time/TimeProviderCustom.cs.meta
- src/unity/Assets/Crest/Scripts/Time/TimeProviderDefault.cs
- src/unity/Assets/Crest/Scripts/Time/TimeProviderDefault.cs.meta
- src/unity/Assets/Crest/Shaders/Ocean.shader
- src/unity/Assets/Crest/Shaders/OceanEmission.hlsl
- src/unity/Assets/Crest/Shaders/OceanFoam.hlsl
- src/unity/Assets/Crest/Shaders/OceanNormalMapping.hlsl
- src/unity/Assets/Crest/Shaders/Shapes/ShapeGerstnerBatch.shader
- src/unity/Assets/Crest/Shaders/Simulation/Resources/ShapeSimFoam.shader
Allows custom time providers. Could give server time, or give a fixed time for automated testing.
Issue #75 
@gamemachine
FYI @moosichu , @dizzy2003
> #75 - time providers

- src/unity/Assets/Crest/Scripts/OceanChunkRenderer.cs
- src/unity/Assets/Crest/Scripts/Reflection/OceanPlanarReflection.cs
- src/unity/Assets/Crest/Scripts/Reflection/OceanPlanarReflection.cs.meta
Move the reflection script update to OnPreRender to hopefully fix jitter with cinemachine - #87
@dizzy2003 @Midda-C
> #87 - cinemachine reflection jitter - move to OnPreRender

- src/unity/Assets/Crest/Scripts/OceanRenderer.cs
This adds the ability to change the viewpoint. Currently need this to change the ocean center to be the boat that the camera is following.
> Add setter for Viewpoint

- src/unity/Assets/Crest/Shaders/OceanEmission.hlsl
- src/unity/Assets/Crest/Shaders/Underwater/UnderwaterCurtain.shader
> Fix shadows not removing caustics in underwater curtain

- src/unity/Assets/Crest/Shaders/OceanReflection.hlsl
> Fix the fact that Planar reflections were not being distorted

- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
Fixes issue where waves jitter after leaving running for some minutes
on platforms like iPhone.
> Fix wave stutter on 16bit GPUs

- crest/Assets/Crest/Crest-Examples/Main/Scenes/main.unity
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs.meta
As discussed on discord - editor-only code that validates a scene setup. Fairly basic checks for now but can be extended going forwards.
Downside is that it might slow down dev very slightly as it may need to be updated when code changes. This is likely to be a small cost though as the code is simple and does not have to be crazy efficient.
Might be usable in automated tests if we want to test scenes/data.
> Scene validator

- README.md
Part of #304, results can bee seen here:
https://github.com/crest-ocean/crest/tree/readme/ships-and-scoundrel#showcase-gallery
> Add 'Of Ships & Scoundrel' to Showcase Gallery

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/BoatProbes.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/FloatingObjectBase.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SimpleFloatingObject.cs
Reason for change described in #308 
Besides being more general, this change exposes less data so is a good change IMO.
Tested in boat scene, seems to work.
> Make FloatingObjectBase expose velocity

- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
> Generate error if collision queried before system init'd

- crest/Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs
Fix #257 
Tested on Unity 2019.2
> Aspect ratio of water camera fix

- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
This is a tiny thing but the condition is reverse here.
> Fix incorrect condition in wave data generation from spectrum

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanReflection.hlsl
This exposes a material variable that multiplies with the reflection alpha, so you can reduce the intensity of the reflection.
> Added ability to adjust planar reflection intensity.

- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
Make the list of ocean chunk renders readonly.
> Cleanup ocean chunk renderers list, thanks @daleeidd

- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
Fix some pretty broken stuff around limits in the query system.
Thanks @daleeidd for spotting these
> Fix query system limits

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs.meta
@daleeidd @skaughtx0r - attempt 2 at cinemachine fix - much simpler than #538 
Push ocean update to 200, which is after cinemachine (100), which seems to make it work for me.
> Cinemachine attempt 2 - update ocean after cine

- crest/Assets/Crest/Crest-Examples/Main/Materials/OceanAlpha_CrestLogo.mat
- crest/Assets/Crest/Crest-Examples/Whirlpool/Materials/Ocean-Flow.mat
- crest/Assets/Crest/Crest/Materials/Ocean-Underwater.mat
- crest/Assets/Crest/Crest/Materials/Ocean.mat
- crest/Assets/Crest/Crest/Materials/Ocean_UnderwaterCurtain.mat
- crest/Assets/Crest/Crest/Materials/Ocean_UnderwaterMeniscus.mat
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanSurfaceAlpha.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMeniscus.shader
I didn't see any issues when testing. I am not able to test SPI with the new XR framework though - only legacy VR SPI. Surprisingly simple to add.
> Add VR/XR Single Pass Instanced support

- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
This attempt 2 of PR i created yesterday #574
This solves problem #523 where queries not working when vsync disabled, which was due to FixedUpdate being called infrequently and query guids were being lost.
This change makes queries persistent, so that it doesnt matter if FixedUpdate is missed for a few frames, but if a query gets too old it is automatically discarded. This is achieved by storing a frame number with the query segment information.
Importantly this PR also recomputes query data segment indices each frame. This effectively compactifies the data every frame, instead of accumulating air bubbles in the data that would waste compute processing.
This should fix the problem, and also not require changes to the API and increased complexity for calling code …
> Store query age and discard old ones. Repack query segments each frame

- crest/Assets/Crest/Crest/Scripts/Helpers/Editor.meta
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/WindowCrestWaterBody.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/WindowCrestWaterBody.cs.meta
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
Part of #361 
Window for creating local bodies of water.
This is similar to what is in #361, except i gave the window a state (idle vs placing) so that it doesnt always show the translation gizmo, and i removed the proxy object option as it only shows when in placement mode.
I also moved some gerstner validation which was firing a warning while gerstner waves were being created.
> Wizard for placing water bodies

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/RippleGenerator.cs
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/RandomMotion.cs
- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
- crest/Assets/Crest/Crest/Scripts/Collision/QueryDisplacements.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/BoatProbes.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SimpleFloatingObject.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrPersistent.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
Related to #587
I just removed what was reported to me as unused by code analyser. I wasn't sure if any of it should go the other way and be used rather than removed.
> Remove unused code

- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- crest/Assets/Crest/Crest/Shaders/Resources/QueryDisplacements.compute
- crest/Assets/Crest/Crest/Shaders/Resources/QueryFlow.compute
Minor but should probably clean up
> PosToSliceIndices - Remove unused param

- crest/Assets/Crest/Crest/Shaders/OceanInputs/FoamAddFromTex.shader
Looks like a simple oversight.
> Fixed "_Strength" parameter being ignored.

- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
Fixes #666 
Thanks for the hint @emaber !
> Set displacement to input properly

- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
Fix for #662 
@skaughtx0r will this fix the issue do you think? I've bumped pool size instead of max requests as a first step.
> Increase query pool size

- crest/Assets/Crest/Crest/Scripts/Helpers/ComputeShaderHelpers.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
Minor but I had a case where the combine shader failed (spuriously) to load resulting in a un-human-readable error. This gives a user facing error and hint to resolve it.
> Give hint if combine shader fails to load

- crest/Assets/Crest/Crest-Examples/Shared/Scripts/UnderwaterEnvironmentalLighting.cs
Status: Ready to merge
Allows control over underwater lighting attenuation
Seems to work well
> Weight control for underwater lighting

- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFoam.cs
Adds a help button link. There should be a way to create an abstraction to reduce boilerplate similar to validated which can be done for release after this one.
> Add foam online help button link

- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsWave.cs
A discord user was hitting instabilities and reported this number to have resolved it.
> Reduce Courant number to improve dyn wave sim stability

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
**Status**: Test / for feedback
Stored as an ITimeProvider to support non-monobehaviour objects
> Make time provider settable from code

- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
While working on something else i could not resist trying the fix-me feature.
You're right it works really well.
> Add fix button for no renderer and for feature disabled

- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
Minor but roll out help links to 'register' scripts
> Help links on register inputs

- crest/Assets/Crest/Crest/Scripts/Spline/Spline.cs
> Add fix functions for not enough spline points

- docs/about/history.rst
- docs/about/known-issues.rst
- docs/conf.py
- docs/index.rst
Adds links to GH issues. Also adds links to Unity Issue Tracker issues we want votes on. Finally, adds links to Unity Graphics Roadmap features we want votes on.
> Add "Known Issues" page

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
Sorry to hit you with yet another review on fix functions but i didnt want to noise up the other PR.
This proposes a few valdiation/fix functions for the depth cache.
> Depth cache fix functions

- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
Random but found these little stragglers that dont seem to be used anymore.
> Cleanup unused vars

- crest/Assets/Crest/Crest/Scripts/Helpers/Hashy.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Hashy.cs.meta
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
Creates a hash from ocean generation settings and uses it to auto rebuild, removing need for rebuild button.
Much more intuitive to use.
I'm not expert on hashing but i think its doing the right thing.
> Hash generation settings

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanNormalMapping.hlsl
- docs/about/history.rst
Adding MegaBoomers fixes to the issue above. Thank you for the fix.
I also propagated the type change as PSSL doesn't like out parameters being different.
Review is best done by commit as I keep those two changes separate.
> Fix black "square" on Quest

- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- docs/about/history.rst
This caused screen to flash black in HDRP
> Fix normal being NaN in rare cases

- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- docs/about/history.rst
- docs/conf.py
Reported by @skaughtx0r on Discord.
There was an extra check which caused a conditional to pretty much always be true resulting in *InitBatches* running every frame for FFTs.
> Fix InitBatches running every frame

- crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
- crest/Assets/Crest/Crest/Shaders/Resources/ClearToBlack.compute
- crest/Assets/Crest/Crest/Shaders/Resources/ClearToBlack.compute.meta
- docs/about/history.rst
Reverts part of  #857 to fix builds for some consoles.
> Revert texture array blit

- docs/conf.py
- docs/user/includes/_hdrp-reflections.rst
Adds SSR setup to the reflections section. I try to push people to learn HDRP through Unity's documentation as much as possible. I think it still covers it well enough since there are no real gotchas for SSR. Let me know what you think.
> Document SSR

- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
- crest/Assets/Crest/Crest/Scripts/Collision/RayTraceHelper.cs
- crest/Assets/Crest/Crest/Scripts/Collision/SamplingHelpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/MultiPropertyDrawer.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/ScriptableObjectUtility.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/WindowCrestWaterBody.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/PropertyWrapper.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrClipSurface.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodTransform.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
- crest/Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Scripts/Spline/SplineInterpolation.cs
- crest/Assets/Crest/Crest/Scripts/Spline/SplinePoint.cs
Add "Crest: " as prefix to all log messages.
> Log message prefix

- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesRemoveGeometry.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesSetHeightToGeometry.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesSetBaseWaterHeightUsingGeometry.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ClipSurfaceConvexHull.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ClipSurfaceSignedDistance.shader
- crest/Assets/Crest/Crest/Shaders/OceanSurfaceAlpha.shader
Adds sea floor offset to shaders that need it.
> Add sea floor offset to missing shaders

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanFoam.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanReflection.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectShared.hlsl
In preparation for adding underwater shader API, I realised some refactoring was needed/desired for the ScatterColour function. There is some housekeeping in there too. Review by commit.
Most changes are to move out the underwater specific code out of the function and into the underwater shader.
> Refactor ScatterColour

- crest/Assets/Crest/Crest/Scripts/Spline/Spline.cs
- docs/about/history.rst
- docs/user/water-bodies.rst
Make it easy to add ocean inputs / features to a spline
> Quick-add buttons for spline features

- crest/Assets/Crest/Crest/Shaders/OceanInputs/FlowAddFlowMap.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/FlowFixedDirection.shader
- docs/about/history.rst
Adds optional UV feathering to Flow shaders.
> UV feathering for Flow shaders

- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- docs/about/history.rst
Disables underwater if ocean layer is not being rendered.
> Fix Underwater not respecting Ocean layer

- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- docs/about/history.rst
Adds validation for underwater keyword and cull mode.
> Underwater Renderer validate Ocean Renderer Material

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
Forgot to implement:
- Underwater tile culling
- Underwater depth fog density multiplier
No release notes as this completes incomplete feature that has yet to be released.
> Fix few missing things for UnderwaterRenderer and WaterBody material

- crest/Assets/Crest/Crest/Scripts/Interaction/BoatProbes.cs
- docs/about/history.rst
Just some basic ones similar to BoatAlignNormal.
> Add query gizmos to BoatProbes

- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- docs/about/history.rst
Shadow passes were running for the ODC camera which this PR prevents.
> Fix shadow flickering when populating depth cache

- docs/about/history.rst
- docs/conf.py
- docs/user/includes/_underwater-shader-graph.rst
- docs/user/underwater.rst
Now that the feature is done for all RPs I have added documentation. It can be found here: https://crest.readthedocs.io/en/docs-ur-shader-api/user/underwater.html#underwater-shader-api
Let me know if you think it makes sense. I am leaning a bit on the example shaders for the shader setup but that should be fine I think.
> Document Underwater Renderer shader API

- crest/Assets/Crest/Crest-Examples/Examples/Shaders/MaskDepth.shader
- crest/Assets/Crest/Crest-Examples/Examples/Shaders/Masked.shader
- crest/Assets/Crest/Crest-Examples/Examples/Shaders/Resources/MaskFill.shader
- crest/Assets/Crest/Crest-Examples/Examples/Shaders/SphereGradientBackground.shader
- docs/about/history.rst
Finally got around to making the Examples scene compatible with XR.
> Fix XR for Examples scene

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
Fixes #1064
More leaks fixed. In this case it was several meshes, materials and scriptable objects.
> Fix several leaks

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- docs/about/history.rst
Had the wrong texture format and negative values where being clamped.
> Fix Sea Floor Depth disabled state

- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
Added *Ocean Renderer > Extents Size Multiplier* to adjust the extents so they can be increased in size to meet the horizon in cases where they do not.
> Add extents modifier

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/RippleGenerator.cs
- crest/Assets/Crest/Crest-Examples/Examples/Scripts/CustomPassForCamera.cs
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/CamController.cs
- crest/Assets/Crest/Crest/Scripts/Editor/BuildProcessor.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/CrestSortedList.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
- crest/Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeWaves.cs
- crest/Assets/Crest/Crest/Scripts/Spline/SplinePoint.cs
- crest/Assets/Development/Editor/AttributeValidator.cs
- docs/about/history.rst
- docs/user/wave-conditions.rst
Reduces or removes several GC allocations. The main reduction is during edit mode or when _Shape Waves > Spectrum Fixed At Runtime_ is false which has been reduced by 3KB per frame.
> Reduce GC allocations

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanReflection.hlsl
- docs/about/history.rst
Not ready to be merged - experimental for now.
> Ramp planar reflection distortion with pixel Z
