- README.md
- src/unity/Assets/Crest-Examples/BoatDev/Scenes/boat.unity
- src/unity/Assets/Crest-Examples/BoatDev/Scenes/threeboats.unity
- src/unity/Assets/Crest-Examples/Scripts/Interaction/InteractCapsule.cs
- src/unity/Assets/Crest-Examples/Scripts/OceanDebugGUI.cs
- src/unity/Assets/Crest/Prefabs/Ocean.prefab
- src/unity/Assets/Crest/Scripts/Collision/CollProviderDispTexs.cs
- src/unity/Assets/Crest/Scripts/Helpers/RenderAlphaOnSurface.cs
- src/unity/Assets/Crest/Scripts/LodData/LodData.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataAnimatedWaves.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataDynamicWaves.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataFlow.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataFoam.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataSeaFloorDepth.cs
- src/unity/Assets/Crest/Scripts/OceanBuilder.cs
- src/unity/Assets/Crest/Scripts/OceanChunkRenderer.cs
- src/unity/Assets/Crest/Scripts/OceanRenderer.cs
- src/unity/Assets/Crest/Scripts/OceanScheduler.cs
- src/unity/Assets/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
@dizzy2003 @Midda-C @moosichu @holdingjason
Hi guys - I've done a refactor that may break existing data and will require fixup, hence this PR.
OceanBuilder had a bit of the key runtime state in it, which led to it being referenced everywhere in the codebase with ugly OceanRenderer.Instance.Builder.XYZW all over the place. This PR moves the state into the OceanRenderer and makes OceanBuilder pure static, which is cleaner and conceptually simpler.
Impact - the OceanBuilder is now a static class instead of a component, and will need to be removed from any gameobjects. Also, the following fields were moved to the OceanRenderer script, and will need to be reconfigured on existing data:
* Ocean material
* Ocean layer name
* Simulation settings - toggles for sims, and the settings fields
This is …
> Remove state from OceanBuilder

- src/unity/Assets/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- src/unity/Assets/Crest-Examples/BoatDev/Scripts/BoatProbes.cs
- src/unity/Assets/Crest-Examples/BoatDev/Scripts/LerpCam.cs
- src/unity/Assets/Crest-Examples/Scripts/Collision/OceanSampleCollisionDemo.cs
- src/unity/Assets/Crest-Examples/Scripts/Collision/OceanSampleHeightDemo.cs
- src/unity/Assets/Crest/Scripts/Collision/CollProvider.cs
- src/unity/Assets/Crest/Scripts/Collision/CollProviderCache.cs
- src/unity/Assets/Crest/Scripts/Collision/CollProviderDispTexs.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataAnimatedWaves.cs
- src/unity/Assets/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
The reason for this change is that ref implies that an input value
can both be read from and written to. However, for some parameters
they were only being read from (so were changed back to pass-by-value,
although the 'in' parameter modifier would be ideal in future versions
of C#).
Furthermore, some parameters were only being written to, so were changed
to `out` parameters.
For further reading see: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters
> Change uses of ref to other modifiers in functions

- src/unity/Assets/Crest/Scripts/LodData/LodDataAnimatedWaves.cs
- src/unity/Assets/Crest/Scripts/LodData/LodDataFlow.cs
- src/unity/Assets/Crest/Scripts/LodData/ReadbackLodData.cs
@moosichu tried to make the tex format robust, constrained and error resistant, while still avoiding the need for a separate channel count field.. for now..
> Make readback texture format robust

- src/unity/Assets/Crest/Shaders/Ocean.shader
- src/unity/Assets/Crest/Shaders/OceanEmission.hlsl
- src/unity/Assets/Crest/Shaders/OceanReflection.hlsl
The previously WIP underwater shader is now much more physically based:
Here's a screenshot of [Snell's Window](https://en.wikipedia.org/wiki/Snell%27s_window) in effect:
The `OceanReflection.hlsl` file is also cleaned-up in general to bring it in-line with the rest of the code base, and the refractive indices of air and water are now exposed and adjustable in the Ocean shader.
> Complete and reintegrate underwater reflection shader

- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
fixes new material instance creation every frame,
resulting slowdown and crash after few minutes.
material property surprising
> this fixes zillion if Underwater material instances creation

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanReflection.hlsl
PR for issue #217.
Note that planar reflections need to be disabled on the ocean material, as this option overrides the reflections.
> Use unity's reflection cubemap

- crest/Assets/Crest/Crest/Scripts/Helpers/PropertyWrapper.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/RenderAlphaOnSurface.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrPersistent.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
In order to make the transition to Compute Shaders as smooth as possible, we are staging the process so that they will initially be implemented with the same structure (and alongside) the existing shaders. As compute shaders do not use Materials for parameter initialisation, we need to roll our own system which can share an interface with the same abstraction that the existing materials use.
> Abstract materials and mpbs to make CS port easier

- crest/Assets/Crest/Crest/Materials/Ocean-Underwater.mat
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanFoam.hlsl
Helps to remove repetition artifacts at distance
Before:
After:
Closeup to show scale preserved:
> Experiment - scale foam textures with lods

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerBatch.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepths.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCache.shader
- crest/Assets/Crest/Crest/Shaders/OceanLODData.hlsl
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateDynWaves.shader
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateFoam.shader
The depths simply represent water depth (not relative ot some deep baseline)  and now the depths can be visualised/debugged directly
This makes the code simpler/better and the system less complex.
> Store depths simply instead of relative to a baseline

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCache.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCacheCommon.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCacheCommon.hlsl.meta
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCacheGeometry.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCacheGeometry.shader.meta
Geometry shaders aren't supported on some platforms, so this
demonstrates that feature for those platforms where they are definetely
not supported.
> Make geometry ocean depth cache shader optional

- crest/ProjectSettings/ProjectSettings.asset
It's a better default to use as the API supports async GPU readback (unlike OpenGL).
> Make Linux default to Vulkan API

- crest/Assets/Crest/Crest/Shaders/Resources/UpdateShadow.compute
HACK INCOMING:
For some reason we get the following error on platforms which target Vulkan:
```
Shader error in 'UpdateShadow.compute': Unknown parameter type (54) for _LightShadowData at kernel UpdateShadow
```
We skirt around this by defining our own _LightShadowData as a float4, and
then making sure that the *real* _LightShadowData variabel is knocked-out.
> Fix shadows on Vulkan platforms

- crest/Assets/Crest/Crest-Examples/Main/Scenes/main.unity
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/OceanDebugGUI.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
Should fix #285.
Made lists of ocean inputs static and moved them outside loddatamgr classes so that registration happens even if ocean structure has not been created. This means scene can initialised without ocean active/present, and it can be enabled later and find its inputs.
> Change ocean input registration to allow ocean to be switched on/off

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCache.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCacheCommon.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCacheGeometry.shader
As discussed on discord. I took one of your thumbs up emojis as a "go for it" :). This might be best reviewed by-commit as i re-org'd them into logical change sets before pushing (mostly).
The main thing to review - it doesnt seem to me that the GS shader feature/multi compile was being used? I tested with GS turned on/off and the new code seems to work (in main.unity).
A future step could be to bring back the multi compile actually, and unify into one shader - it might be that only one line in the .shader file needs to be turned on/off with the multicompile:
#pragma geometry Geometry
> Refactor depth cache shaders

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
Furthermore, cleanup how geometry shader support is reported in general.
The big change is that we now just disable geometry shader support on
all mobile devices, as they don't seem to have good support for them
anyway, even for APIs where they have them.
Resolves issue #290.
> Disable geometry shaders on PS4

- crest/Assets/Crest/Crest/Scripts/Helpers/PropertyWrapper.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodTransform.cs
Makes it gracefully(ish) allow editing scripts and recompiling in play mode.
Its a shame about making the kernel indices non-static. An alternative would be to reinit them when a compilation is detected. Given that LodDataAnimWaves is basically a singleton anyway, i thought the below is ok.
Making RenderData serializable has the side effect of making it visible in LodTransform inspector, which is actually quite cool as it can be inspected at runtime.
> Fix edit and continue in editor

- crest/Assets/Crest/Crest-Examples/Whirlpool/Scripts/Whirlpool.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
Max detail height - camera height relative to sea level where ocean is to minimum scale to maximise detail - was affected a lot by . It caused it to lower which mean ocean was not at full when camera was around sea level. Some lowering is ok - helps for gerstner waves which drop the average surface height lot - but the whirlpool should not lower it, so i've split out some so it can distuingish between gerstner displacements and other.
Editorial note: i doubt this is going to make any sense. maybe we can discuss it tomrrow. a second pair of eyes on testing might be useful if you find the time, no worries if not.
> Max detail height affected only by waves

- crest/Assets/Crest/Crest/Materials/Ocean-Underwater.mat
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateFoam.compute
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateShadow.compute
This avoids objectional boundaries between cascades that visible when the camera moves around, in the shadow and foam. The result is much more robust now.
> Sample in data from larger cascade for foam and shadow

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
The ocean detail was being driven relative to the origin, instead of relative to sea level.
Zooming out i've been unable to find code i'm happy with for driving the detail level, but i thought it might help to expose a param for dropping the sea level a bit when theres large waves to help visual range. This has been hardcoded for a while and shouldn't need to be tweaked in most circumstances, but might help for some people.
Resolves #324.
> Fix ocean detail missing away from y=0

- crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
Recently number of octaves changed, these checks need to catch legacy
data
Response to #322 which gave unclear error messages
> Improve checks/errors around sampling spectra

- crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrPersistent.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
We werent clearing data for e.g. dyn waves, so it could start with nans or etc in it i guess. This change appears to fix the issue.
> #322 - Clear persistent data so that it doesnt end up with random garbage

- crest/Assets/Crest/Crest-Examples/Shared/Scripts/OceanDebugGUI.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Shaders/OceanLODData.hlsl
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.compute
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.shader
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.shader.meta
Another variation of a fix for #279 . I think this might be a 'winner' (or at least the best loser) - doesnt add complexity to the code beyond the minimum (a new combine code path).
Adds a few texture copies, but avoids a few downsides of #340 .
I've lazily left both code paths in the runtime. This has an overhead of loading an additional shader, and allocating an additional widthXheightX1 texture. To fix this we could move a bunch of stuff into defines potentially. Might be a good idea to deploy it as a dynamic switch which might help with debugging and then bake it into a define later perhaps? Or just leave it dynamic.
> Ping pong combine

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
Foam Light Scale isn't specific to Foam 3D Lighting. It is also applied to foam generally on this [line](https://github.com/crest-ocean/crest/blob/master/crest/Assets/Crest/Crest/Shaders/OceanFoam.hlsl#L80).
> Move Foam Light Scale under Foam header

- crest/Assets/Crest/Crest/Materials/Ocean-Underwater.mat
- crest/Assets/Crest/Crest/Materials/Ocean.mat
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanReflection.hlsl
Used to put too-fine surface detail into material. Gives widening of specular response in distance.
Detail moves from surface shape, to normal map, to microfacets
https://hal.inria.fr/inria-00443630/file/article-1.pdf
> Vary material roughness in distance

- crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
Resolves: #351
The aim is to reduce confusion when authoring or debugging since before
the fix the disabled slider would still affect the spectrum. Option 4
out of the following options was chosen:
1. Leave as is. This is expected behaviour
2. Find the next highest power that is enabled
3. Skip interpolation
4. Use the minimum power
> Spectrum power lerp should check disabled flag

- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.compute
_LD_TexArray_AnimatedWaves_Compute is now half4 instead of float4
to match the type of the underlying texture.
> Fix the UAV type of shape combine texture array

- crest/Assets/Crest/Crest/Scripts/GPUReadback/GPUReadbackBase.cs
Fix for #358 
DWP2 requires sampling data tag should not be null. But not every lod level data returns a valid Rect to compare the position.  So, returning the last lod level with a valid Rect data while containing the `lastCandidate` constraint is a tricky fix for the issue.
> Fix DWP2 Invalid sampling data error

- crest/Assets/Crest/Crest-Examples/Whirlpool/Materials/Ocean-Flow.mat
- crest/Assets/Crest/Crest/Materials/Ocean-Underwater.mat
- crest/Assets/Crest/Crest/Materials/Ocean.mat
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
Sorry if having a few small fixes in a single PR is an issue. It was just the most efficient way. I can redo as separate PRs if desired.
Incomplete refactor: `parms` was years ago
`IndexOutOfRangeException` was due to "slice index + 1" so adding an extra element is correct I believe
`_SubSurfaceCrestColour` was from the now removed height lerp subsurface colouring
> Minor fixes

- crest/Assets/Crest/Crest-Examples/Shared/Scripts/OceanDebugGUI.cs
- crest/Assets/Crest/Crest-Examples/Shared/Shaders.meta
- crest/Assets/Crest/Crest-Examples/Shared/Shaders/Debug.meta
- crest/Assets/Crest/Crest-Examples/Shared/Shaders/Debug/TextureArray.shader
- crest/Assets/Crest/Crest-Examples/Shared/Shaders/Debug/TextureArray.shader.meta
Resolves #277. Not my first issue, but I am very green when it comes to these things so I thought I would give it a try. Followed the following:
https://docs.unity3d.com/Manual/SL-TextureArrays.html
I went with the simplest approach which is a shader to render a specific depth of the texture array. I placed it under `Crest-Examples` since that is where the `OceanDebugGUI` lives.
I made some other optimisations and a minor design change. If you want to use the old layout, then I can easily change it back (but still have it optimised).
Before:
After:
Tested on MacOS with 2018.4 and 2019.2
> Ocean Debug GUI optimisations

- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
Continues on from issue #364
Overwriting is for quality of life. Otherwise, you would have to remove the texture property, bake, replace and finally delete the old texture. It can track path changes so users can rename GUID name if desired. GUIDs are used to avoid conflicts.
> Baked depth cache improvements

- crest/Assets/Crest/Crest-Examples/Shared/Scripts/OceanDebugGUI.cs
- crest/Assets/Crest/Crest-Examples/Shared/Shaders/Debug/TextureArray.shader
TextureArray shader
- Use code style similar to other shaders
- Use unity_ColorSpaceDouble to brighten textures
- Use newer UnityObjectToClipPos
- UV only needs to be float2
OceanDebugGUI
- Make bottom bar full width if sidebar hidden
> Ocean Debug GUI housekeeping

- crest/Assets/Crest/Crest-Examples/Main/Scenes/main.unity
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
Status: ready for review by commit. @moosichu / @daleeidd let me know if you are up for taking a look.
The validation code on the ocean depth cache was split into two places.
This change unifies it into one place and has an option to perform the validation on Start() (in addition to the 'Validate' button in the OceanRenderer inspector) which defaults to true. This way people get the full validation by default and can disable it if desired.
Added a validation error for the depth cache Y scale being 0, which breaks the cache population.
> Unify depth cache validation

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCache.shader
I think this should be ok. Half precision didn't work in the past because the depth used to represent 'height' so had bad precision at shallow depths, and the artifacts were obvious. Now that its properly water depth it seems to work fine.
Add a couple of minor extras to explicitly target the R channel.
I tested in main which has a fairly large variation in sea floor depts and it seems fine to me.
@daleeidd @moosichu let me know if you have thoughts!
> Reduce depth precision to half

- crest/Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs
Disable rendering shadows into the planar reflection. This cut the planar reflection render time in half for my project, from about 2.2ms to 1.2ms.
> Performance optimization, disable shadows when rendering planar reflection.

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanReflection.hlsl
Not sure this is desireable, but if it is this may be helpful in reflections.
Commit Description:
This probe sampling code is based on the Unity PBS standard shader and interpolation code suggested by https://catlikecoding.com/unity/tutorials/rendering/part-8/.
It should blend probes, which I think was not taking place before, and also it should make reflection smoothness depend on the Ocean specular parameter.
> Added Unity PBS Reflection Probe Sampling

- crest/Assets/Crest/Crest/Scripts/BuildCommandBuffer.cs
- crest/Assets/Crest/Crest/Scripts/Collision/CollProviderNull.cs
- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
- crest/Assets/Crest/Crest/Scripts/Collision/QueryDisplacements.cs
- crest/Assets/Crest/Crest/Scripts/Collision/QueryFlow.cs
- crest/Assets/Crest/Crest/Scripts/Collision/VisualiseCollisionArea.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrClipSurface.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrPersistent.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodTransform.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
Ready to merge.
One of our users needs this with a priority if possible. @daleeidd if you're working today could you please give this a review? If not it's fine. Thanks!
The speedup entering/exiting playmode when domain reload is disabled in 2019.3 is incredible.
As noted in #373, crest did not support this option before now.
If the domain is not reloaded, any static variables will retain there value across the transition. There is a special callback that can be used to initialise these variables if needed. More info: https://docs.unity3d.com/2019.3/Documentation/Manual/DomainReloading.html
Some of our statics don't need to be reset across reloads. Some statics didnt need to be statics at all (for example, some shader param ids where private, and members of a class that were basically a …
> Support no domain reload

- crest/Assets/Development.meta
- crest/Assets/Development/Editor.meta
- crest/Assets/Development/Editor/Crest.Development.Editor.asmdef
- crest/Assets/Development/Editor/Crest.Development.Editor.asmdef.meta
- crest/Assets/Development/Editor/WindowCrestDashboard.cs
- crest/Assets/Development/Editor/WindowCrestDashboard.cs.meta
Status: Ready to merge
This is a general purpose window to add dev stuff, but would not be intended to be included in published packages. Hence it is put outside the main crest folder.
So far it has scene loading buttons.
We could add buttons to resave SGs or to do other automation.
Thoughts @daleeidd / @moosichu ?
Thanks!
> Simple first version of dashboard

- crest/Assets/Crest/Crest/Scripts/BuildCommandBuffer.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Shaders/OceanHelpersDriven.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ClipSurfaceConvexHull.shader
Before, the CSCH (clip surface convex hull) appeared to work pretty well. But once there was enough waveform displacement, due to chop and possibly other sources, the clipped area would become less accurate to the point where it would no longer appear.
This samples the displacement using the same code as the query displacement compute shader. Four iterations works well when testing which is what the other shader used too. I am not sure how we should set the minimum slice. I found that two was a good value. But it should probably be influenced by `_TexelsPerWave`?
I will need to add some documentation. Should I delete the old function (the first `SampleOceanDataAtWorldPosition`)?
> Use displacement for clip surface convex hull

- crest/Assets/Crest/Crest-Examples/BoatDev/Data/BoatAlignNormal.prefab
- crest/Assets/Crest/Crest-Examples/BoatDev/Data/BoatProbes.prefab
- crest/Assets/Crest/Crest-Examples/BoatDev/Materials/WaterInteractionBoatAlignNormalBack.mat
- crest/Assets/Crest/Crest-Examples/BoatDev/Materials/WaterInteractionBoatAlignNormalFront.mat
- crest/Assets/Crest/Crest-Examples/BoatDev/Materials/WaterInteractionBoatProbes.mat
- crest/Assets/Crest/Crest-Examples/BoatDev/Scenes/Internal/BoatSceneCore.prefab
- crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs
**Overview:**
Weight input on script and Strength input on the material are multiplied
together. This causes confusion as people arent sure what the difference
between the two is.
This change fixes the weight at 1, leaving only the strength param. Some
weights were set > 1, this change bakes that into the materials.
**Tests:**
Ran boat scenes in editor and verified wakes and other interactions look unchanged.
**Issues:**
If people have weights that aren't 1, this change will suddenly increase the strength of the interaction. I suggest to mitigate this with release notes.
> Remove duplicated weight/strength input on object-water interaction

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
This will allow ordering between clip shaders (include before remove). This change is taken from the `feature/local-water-bodies` branch where it seems to work.
Merging this into master should have no impact on existing content/functionality whatsoever as there are no order dependencies that I'm aware of between current inputs, so it should be inconsequential if the order the inputs are submitted changes.
It could conceivably add a bit of extra cost to adding/removing ocean inputs due to the sorting, but the number of inputs will rarely be large so it seems unlikely it will ever be an issue.
> Sort ocean inputs based on render queue

- crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
Zero state for sea floor depths is red. Before this, it was black which makes the ocean completely flat and maxes foam values.
Is using a white texture like so suitable?
Also, should I go through and `BindNull` for depths everywhere else to be safe? The one I added wasn't necessary to fix this issue, but might be a good idea to be safe.
> Fix sea floor depths being at maxed value when not enabled

- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ClipSurfaceRemoveArea.shader
It can return values less than 1 which is not intended.
> Don't rely on auto-generated shader for remove area

- crest/Assets/Crest/Crest/Scripts/BuildCommandBuffer.cs
- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/ComputeShaderHelpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/ComputeShaderHelpers.cs.meta
- crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrPersistent.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
A common issues users have is that compute shaders won't load correctly through no fault of their own. However, previously Crest would just null-reference exception all over the place without a clear indication to the user as to why.
This change aims to ensure two things:
- When a compute shader fails to load, we give a good error message explaining that and provide a common solution.
- Crest no longer spams the log with new null reference exceptions every frame if the compute shaders fail to load.
The first point is achived by replacing the calls to `Resources.Load` to a call into a wrapper which asserts if the load fails.
The second point is achived by finding all the bits of code which only run under the assumption that compute shaders will successfully load, and ensure that they now …
> Make Crest handle failed compute shader loads more gracefully

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
Motivation:
LINQ functions, whilst convenient can be slow and generate more gargbage than neccessary. This change was motivated by #432 an is incredibly minor.
The main reason I'm making a PR for this is because I noticed that Texture2D has a new NativeArray API: https://docs.unity3d.com/2018.4/Documentation/ScriptReference/Texture2D.GetRawTextureData.html
I looked into using it, but in the end I went for the safe incremental improvement. But I thought it would be worth highlighting this as an option we could start using in the future.
> Make array initalisation use loop instead of LINQ

- crest/Assets/Crest/Crest/Shaders/Resources/UpdateShadow.compute
Fixes #449.
We already had the problem from the issue (UpdateShadow compute shader not compiling) on Vulkan, so applying the same fix to Metal was a straightforward thing to do.
Honestly though, I think part of the issue does come from the fact that we are trying to do this shadow stuff in a compute shader, and unfortunately Unity doesn't support having standard shaders target a specific slice in a texture array until 2019.1 (which is why we don't do this with a compute shader in URP), so we have to stick with the compute shader in BIRP for now.
> Make _LightShadowData knockout apply to Metal as well

- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanLODData.hlsl
- crest/Assets/Crest/Crest/Shaders/Resources/QueryDisplacements.compute
- crest/Assets/Crest/Crest/Shaders/Resources/QueryFlow.compute
Status: Ready to merge.
The all time silliest issue in crest. Theres a bunch of cases where we can compute log(0). This is a bad time as it gives -INF on hlsl.
This might be causing particular badness on metal - some instrumentation i added for someone reported a NaN coming from the height queries, which led to finding this. Hopefully this change helps or resolves the issue, but in any case it is necessary.
> Ouch - fix a ton of unprotected logs, all of which may produce NaNs

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Shaders/OceanGlobals.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanHelpers.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanVertHelpers.hlsl
Computes the LOD black point fade from the mesh density. By computing the value we reduce gaps between tiles for lower mesh densities and reduce popping for higher mesh densities.
First discussed in #456. It helps solve one cause of that problem.
The formula is based on hand crafted values that produced no gaps when ocean
is flat. It works pretty well when displaced too.
The approach to getting these values is to have a range parameter which sets the black point fade value for easy testing. The ocean needs to be flat. Then in play mode, switch to the scene view to show the camera and surrounding ocean tiles. Moving the camera around will expose gaps (even vertically). Change the black point value and repeat until no gaps appear.
It is still not 100% perfect as displacement can still …
> Compute LOD black point fade

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Shaders/Misc.meta
- crest/Assets/Crest/Crest/Shaders/Misc/OceanProxy.shader
- crest/Assets/Crest/Crest/Shaders/Misc/OceanProxy.shader.meta
**Status:** ready to merge
Creates a transparent plane at the ocean height in the scene at the sea level, to use as reference.
Creates a hidden, nonsaved transparent plane gameobject. Done this way because it doesnt seem to be possible to have gizmo drawing intersect with the scene.
Only creates if in edit mode and proxy is enabled.
Tests: in win64 editor, and made win64 standalone build.
> Show a proxy plane at the ocean sea level

- crest/Assets/Crest/Crest-Examples/Whirlpool/Shaders/Resources/FlowWhirlpool.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/FlowAddFlowMap.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/FlowFixedDirection.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepths.shader
Fixes #488 
The error produced from this is because of the Material Preview in the Editor. This error does not stop the shaders from working correctly.
I've submitted a bug report to Unity. We could ignore this or revert it once fixed.
> Fix Material Preview error on Metal: not enough components in fragment shader

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- crest/Assets/Crest/Crest/Scripts/Collision/SamplingHelpers.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SimpleFloatingObject.cs
This is a big pitfall that is too easy to get wrong - the intuitive
thing is to reuse SampleHeightHelper multiple times, but it will
simply overwrite the query position before the result is sent
to the GPU (if the compute height queries system is used).
This change throws a warning if the position is set multiple times
in a frame.
Unfortunately there is a case where this is valid - FixedUpdate can
be called multiple times per frame. I added an arg to indicate this
which will suppress the warning. Some collision providers will be
happy to receive multiple queries per frame. The compute height
query system will just overwrite the query pos and send off the
final (last) fixedupdate position to the GPU. This is imperfect but
I don't see how this can work better.
> Warn on reuse of a SampleHeightHelper multiple times in a frame

- crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
Previous attempt: #432 
I wasn't diligent with this one. It fixed the foam problem but nothing else. The issue that remained is when the ocean depth is disabled, the value would be clamped to 0-1 due to not being an HDR texture.
I tested it on Metal, DirectX and Vulkan. I am using the [RGB9e5Float](https://docs.unity3d.com/ScriptReference/TextureFormat.RGB9e5Float.html) format. It appears to be well supported.
The alternative is to map the depth values to 0-1 instead.
> Fix ocean depth disabled state properly

- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
In the compute height query system, queries are made with an identifying GUID. This registers the query and the GUID is used to track it across frames.
Right now we are never flushing GUIDs which is bad. The code is manually populating the registrar with last frame's guids every time its acquired. The number of query GUIDs grows montonically, eventually throwing the "max guids" error.
I believe queries are uploaded and processed if they are present, even if they're no longer being actually used.
This code avoids repopulating newly acquired query registrars with previous frames' GUIDs. This seems to work and it seems like a better solution.
I also added a line to the gui overlay to report how many guids there are in each frame's results.
> Flush query guids every frame

- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcessUtils.cs
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanConstants.hlsl
- crest/Assets/Crest/Crest/Shaders/Resources/OceanUnderwaterMask.shader
- crest/Assets/Crest/Crest/Shaders/Resources/UnderwaterPostProcess.shader
@huwb did the legwork for this one in another branch that was then back-ported to BIRP. The plan here is to ensure that the flickering horizon line no longer appears in the distance by moving the calculations for that to the CPU.
It's less of a problem than it was before, but it's still present. Unfortunatley single-pass rendering doesn't work with this either, even though I believe that I have made the requisite changes to ensure that it should work.
The horizon line can still appear incredibly rarely unfortunately, the next step is going to be trying to move some of the calculations to doubles of possible.
> Move far plane calculations to the CPU

- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
Without this, if flow is enabled on material, visible flow will occur as unity binds a non-null texture to the slot.
I think this has appeared in some issues, i just didnt understand why it was happening until now.
> If flow data not avail, bind null flow

- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
Scales the caustics strength by primary light colour, depth fog density and scene depth.
Solves the problem of caustics showing up under underwater lights when they shouldn't. This solution works independently from the _UnderwaterEnvironmentalLighting_ component, but it is affected by it since it scales the primary light. But that is a separate problem.
I am not certain how they should co-exist with depth of field and focal depth, but right now they don't appear to conflict.
I plan to port this to HDRP to replace limiting caustics by scene depth, but it might be a bit more involved due to different lighting units.
> Scale caustics strength by primary light and depth fog

- crest/Assets/Crest/Crest-Examples/Shared/Prefabs/Internal/DemoCameraCore.prefab
It was set to 100k which is huge, much bigger than previous projects i've worked on.
This large distance meant the ocean (with default settings) was not covering the frustum, messing up the ocean mask.
I think this is a good change and safe. Tested demo scenes and they look fine to me in editor.
> Reduce far plane distance to 10000

- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcess.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcessUtils.cs
Shimmies the horizon-line up and down based on the camera position. It's a hack but it's pretty-robust. This commit also takes into account the world space height of the camera frustum for determining wether or not to force the post-process shader to run full-screen, fixing an issue where this would kick-in prematurely if the ocean didn't have any waves which I was using to test the horizon-line fudge.
Will fix #456 when it's merged into HDRP.
> Add dynamic horizon line safety margin prevent artifacting

- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcessUtils.cs
This ensures that for when we disable chunk rendering in the scene
hiearchy for things like local water bodies or other optimisations, if
they will still be correclty renderered as part of the ocean mask which
assumes that chunks will always form a continous surface for the post
process effect to work accurately.
> Initiliase chunks for ocean mask even if it's disabled in the scene hiearchy

- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcessUtils.cs
Manually set a bool on each ocean chunk that checks if the data is bound, a simpler and more general solution anyway. 
Fixes #479, the repro was harder as we were rendering the mask chunks even if culled in the latest release, but this was causing gaps to appear which now seem to be fixed.
> Bind Ocean Mask Data for ocean chunks not rendered due to occlusion culling

- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcess.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcessUtils.cs
Only apply the horizon safety margin multiplier to horizon if and only
if concrete height of the camera relative to the water and the height of
the camera relative to the sea-level are the same. This ensures that in
incredibly turbulent water - if in doubt - use the neutral horizon.
Fixes #520 
I tested this in the three boats scene in HDRP, the incredibly localised water spike caused by the ocean liner was causing trouble, so this change makes the horizon-safety-margin multipler much more conservative and has worked really well in testing. 
Justification: the check that I have added essentially checks to see if the camera is inside a swell or a dip - in that case there is no need to apply the horizon safety margin multipler is counter-productive (and with time we might find that applying …
> Zero horizon safety margin multiplier if in doubt

- crest/Assets/Crest/Crest/Shaders/OceanReflection.hlsl
Reported by jRocket on Discord. If more than four layers is used on terrain, these layers will appear black in planar reflections.
If I disable HDR on the planar reflection script, it works as expected. So it appears that Unity is packing the alpha channel to achieve layering.
Saturating the alpha fixed this. I don't think this is an issue for anything else. Not sure if there are any negative implications of taking this route.
> Fix terrain with more than four layers being black in planar reflections

- crest/Assets/Crest/Crest/Scripts/Helpers/AssignLayer.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/FloatingObjectBase.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsBase.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
**Status**: Proposal. Do not merge
The proposal is that the above would compliment current validation approach (_OceanValidation_) and possibly replace other forms of validation like logging on play.
The benefit is it gives instant feedback to the user and does not pollute the console which people are sensitive to.
~~There are two approaches to how we target an inspector, and three approaches on how we compose and presenting the help boxes (awkwardly worded but might make sense in a bit).~~
Being a proposal code quality, naming etc is pretty poor. So please forgive me for that. Mainly to demonstrate the idea to see if we want to pursue further.
We are using an interface and unfortunately we cannot target interfaces (but we can target through inheritance which is better than nothing).
1. …
> Help Box Validation Messages

- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
Issue reported in #539 
This seems to happen if no view of the game is rendering, then the async readbacks do not return and things get clogged up. I've never heard of this occuring 'in the wild' in normal circumstances.
With this change, queries will stop getting sent off, and new queries will just overwrite old queries in place until things start up again.
> Gracefully fail if segment registrar scratch exchausted

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs.meta
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
Thought i'd try a fun experiment - give a easy way to enable/disable GUI fields based on other fields. Example:
Here the 'search..' option is disabled because a Light is provided in the reference field above it (so no search will be done).
I find this kind of behaviour useful to know what parameters are active, and to help understand how a system works.
Issue: When multiple property drawers are provided, only the first one takes effect. Unforunately this means this feature can not be used in conjunction with another drawn attribute like `Range()`.
Let me know what you guys think.
> Predicate enabled/disabled state of GUI based on a named property

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- crest/Assets/Crest/Crest/Scripts/Collision/CollProvider.cs
- crest/Assets/Crest/Crest/Scripts/Collision/CollProviderNull.cs
- crest/Assets/Crest/Crest/Scripts/Collision/FlowProvider.cs
- crest/Assets/Crest/Crest/Scripts/Collision/FlowProvider.cs.meta
- crest/Assets/Crest/Crest/Scripts/Collision/FlowProviderNull.cs
- crest/Assets/Crest/Crest/Scripts/Collision/FlowProviderNull.cs.meta
- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
- crest/Assets/Crest/Crest/Scripts/Collision/QueryDisplacements.cs
- crest/Assets/Crest/Crest/Scripts/Collision/QueryFlow.cs
- crest/Assets/Crest/Crest/Scripts/Collision/SamplingHelpers.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/BoatProbes.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SimpleFloatingObject.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
This was something that I didn't get to as part of the ocean-in-edit-mode changes - making the query system standalone objects rather than monobehaviours, as there is no advantage to having them that way. Further i discovered that disabling scene reload broke the system, so i decided to move it away from behaviours now.
The resulting code in this PR is simpler, and more direct/explicit, and less stateful.
I'm not aware of any issues.
I tested in win64 editor and a standalone build.
> Un-monobehaviour compute query system

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/LerpCam.cs
- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/RippleGenerator.cs
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/Interaction/InteractCapsule.cs
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/UnderwaterEnvironmentalLighting.cs
- crest/Assets/Crest/Crest-Examples/Whirlpool/Scripts/Whirlpool.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/RenderAlphaOnSurface.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/BoatProbes.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteractionAdaptor.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs
I just when through and added null checks for a few more components. It might seem excessive, but we have already received a support request this issue.
> Bail early when ocean instance is null

- crest/Assets/Crest/Crest-Examples/Shared/Prefabs/Internal/DemoCameraCore.prefab
- crest/Assets/Development/Editor/WindowCrestDashboard.cs
- crest/Assets/Development/Scenes.meta
- crest/Assets/Development/Scenes/Internal.meta
- crest/Assets/Development/Scenes/Internal/TestScene.prefab
- crest/Assets/Development/Scenes/Internal/TestScene.prefab.meta
- crest/Assets/Development/Scenes/Internal/TestSceneCore.prefab
- crest/Assets/Development/Scenes/Internal/TestSceneCore.prefab.meta
- crest/Assets/Development/Scenes/Test.unity
- crest/Assets/Development/Scenes/Test.unity.meta
- crest/Assets/Development/Scripts.meta
- crest/Assets/Development/Scripts/Crest.Development.asmdef
- crest/Assets/Development/Scripts/Crest.Development.asmdef.meta
- crest/Assets/Development/Scripts/TestCameraChange.cs
- crest/Assets/Development/Scripts/TestCameraChange.cs.meta
- crest/Assets/Development/Scripts/TestDynamicResolution.cs
- crest/Assets/Development/Scripts/TestDynamicResolution.cs.meta
- crest/ProjectSettings/ProjectSettings.asset
For testing:
- Camera switching
- Dynamic resolution
We have had problems with both for underwater. I have used version defines so it works in both built-in and SRP.
I have also enabled _Allow Dynamic Resolution_ on the camera and _Enable Frame Timing Stats_ in the project settings to stop Unity complaining on the camera inspector.
> Add dynamic resolution and camera change test components

- crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
Fix for issue #542 
This was actually a pretty bad bug - disabled octaves use the min power
value, and it was not small enough, so the gerstner was always generating
waves (even with octaves disabled or turned down to '0').
Tested that this was low enough to remove all waves in current spectrum
wavelength range.
This should not break existing data.
> Reduce min wave power to avoid persistent small waves

- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
Solution provided by @akeidonas in #491
Looks correct after testing. Threads groups will max out at 64. I never could reproduce the original issue as reported so that failure is probably hardware dependent.
> Fix incorrect thread group size

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
I was noticing popping in VR. Narrowed it down to the shallow subsurface scattering.
Pops exhibited with camera transform X and Z values between 39.201 and
39.205. 0.0001 seems to eliminate it entirely.
It probably wasn't that noticeable in 2D with certain ocean material settings. Specular etc can mask the problem enough. And 2D type of movement would probably skip past it.
It affects both BIRP and URP. Not sure about SG.
> Fix Shallow Subsurface Scattering popping

- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesGerstnerBatchGeometry.shader
Option to use vertex colour as weight to scale waves, when using the gerstner-from-geo shader. This was the ultimate intention but did not have test data before.
@EliGould tested this and indicated it works well.
> Scale gerstner waves using vert colours

- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs.meta
**Status**: Ready for review
A piece of the local-water-bodies branch that can be merged in separately.
This change adds a `WaterBody` component which registers its AABB with the ocean. During update, if there is one or more water bodies present, bounding box overlap checks will be performed between each ocean tile and each water body. If there are no overlaps, the tile is turned off. Turning off a tile means OnWillRenderObject will not get called, no culling will be performed, no draw call, etc, so this is a nice early off-switch where water should not be present.
These changes unify the code a bit towards what is in HDRP. The HDRP version also loops over the tiles for underwater purposes and i expect we will be able to combine concerns nicely.
**Testing**:
Add WaterBody component to a …
> WaterBody script for tile culling

- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
When changing the mode (global or geometry) on the _ShapeGerstnerBatched_, it would not be applied because the initialisation steps were already done.
This also fixes the render proxy duplicating every time _InitBatches_ is
called (which is enter/exit play mode).
And lastly moves validation code into _Validated_.
It was sort of all tied together... o_o'
> Fix ShapeGerstnerBatched mode not applying when changed

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesAddFromTex.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesGerstnerBatchGeometry.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerBatch.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
Required no scripting changes. I haven't tested everything yet, but I am confident it works fine. Providing we enable keywords on the material instead using Shader.EnableKeyword (which we do. Other than for the compute shaders where I think we need them for the moment at least).
This might break someone's project if they need global keywords with Crest. But I don't really see why they would.
> Use local shader keywords

- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
Part of the ocean-in-edit-mode changes included having the depth cache automatically populate itself every frame when in edit mode. This was to have the ocean automatically respond to changes in the terrain/sea floor depth.
In 4.4 we fixed a bug where the cache was always populating every frame, and it was found because populating the cache is a significant cost for realistic scenes which users noticed.
I regret making the depth caches update every frame - I feel automatically responding to changes in terrain is not worth the significant performance/power cost of populating the cache every frame. This PR disables that behaviour and instead ensures the that *Populate cache* button is visible in the inspector so that users can populate it themselves if they change …
> Depth cache populate on demand instead of every frame

- crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
Mostly to fix things mentioned in #557.
Fixes
- Fix broken button state by replacing with enum
- Fix undo/redo only working for some properties
- Fix some properties not serialising
Improvements
- Disable power sliders if power is disabled
- Show minimum power if power is disabled
- Hide power arrays (replaced with tooltip over slider to see value)
- Hide/show options based on spectrum model
- Spectrum model is now persistent
> Improved wave spectrum inspector

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrPersistent.cs
Fixes #588 
The issue was the __BindData_paramIdPosScales_ not being set as suggested by @huwb. I went with just calling _BindData_, but we could set only that property.
> Fix dynamic waves crashing without flow or depth sims

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/LerpCam.cs
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/Collision/OceanSampleHeightDemo.cs
- crest/Assets/Crest/Crest/Scripts/Collision/SamplingHelpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/BoatProbes.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SimpleFloatingObject.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
My 'out game' has not been on point in the past, some annoying cruft can be removed by moving the sampling helpers to use out params.
Let me know what you think
> Use 'out' which allows some reduction around the sample helpers

- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcessUtils.cs
Fixes #572
There is probably a proper way to fix this in the horizon calculation. But this seemed like the easiest way for me.
All it does is check to see if the horizon is within the far clip plane. And if it is not, set the _Horizon Safety Margin Multiplier_ to zero since this is the cause of the bar of underwater fog.
Is there a reason we are using the _camera.farClipPlane_ value rather than a hard-coded one?
> Fix underwater effect appearing at top of screen when looking up

- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
Fixes #585 by fixing both the displacement reporting and reverting shared mesh usage.
Displacement reporting had shared state that was being overwritten which is now fixed. There are still some very minor issues with displacement reporting. I have to freeze time to get correct culling when using the frame debugger. It works fine otherwise. I think using delegates and making Crest more event oriented should help with this further.
And lastly there is moving away from shared meshes. We will lose instancing as a result, but culling is more important. Using sharedMesh in the editor is still correct from testing. The mesh bounds gizmos don't expand in edit mode, but using a mesh instance didn't appear to fix it.
I've also added a custom inspector to show the renderer bounds in the inspector.
> Fix ocean tiles frustum culling

- crest/Assets/Crest/Crest/Shaders/OceanHelpers.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanVertHelpers.hlsl
I have been seeing gaps in the ocean tiles at particular coordinates. It appears to be a precision issue in the grid. This is not screen resolution dependent so you should be able to reproduce with provided example scene.
Without fix
With fix
I am not sure if this is just my machine or not. I would think I would have noticed this when developing the black point fade fix which was developed on different machines. I had a look at the LOD fade and it didn't have any affect on this issue.
It appears when either the X or Z coordinates is nearly divisible by 8 (so 7.999997 or 15.999997). The gaps will appear in different locations depending how large the whole number is.
_Geometry Down Sample Factor_ has an affect but only a value of 8 clears it without the fix.
Increasing _2.0_ by _0.000001_ …
> Fix precision issues in grid

- crest/Assets/Crest/Crest-Examples/Shared/Scripts/CamController.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcessUtils.cs
Hopefully fixes #520
Solves a handful of edge cases for the underwater horizon.
The horizon normal would sometimes be inverted when camera has +/-90° roll which may have been due to precision errors. I have added a fuzzy check to catch this.
The margin was added the horizon position up. But up will be along the normal when the camera is rolled. This result in the multiplier either having no effect or the opposite effect. I just used then normal to take roll into account.
The camera position to sea level was being used for the safety margin which lead to it sometimes covering a quarter of the screen. I have changed it to only use the sign so the margin's size is determined by the multiplier property. This fixed a lot of edge cases where checks to disable the margin failed.
The ocean …
> Fix underwater safety margin edge cases

- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
The shadows are projected after being sampled so they align with the shadows on the scene. But it is currently using the projected position which includes a fudge factor. This calculates the projected position without the fudge factor.
The fudge factor does the following:
> project along light dir, but multiply by a fudge factor reduce the angle bit - compensates for fact that in real life caustics come from many directions and don't exhibit such a strong directonality
Before
After
> Fix caustics shadows projected position misalignment

- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
I had a nasty case where i was adding an anim waves input which had
displacements, and since the correction was on by default, there was
a feedback loop where the displacement in the input moved the input
itself around. This disables correction on anim waves inputs by default.
I looked for a fancier way to do this (rather than duping some code)
but settled on this.
Also the tooltip was wrong on the gui, fixed.
> Update displacement correction policy for ocean inputs

- crest/Assets/Crest/Crest/Scripts/Helpers/PropertyWrapper.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrPersistent.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
Removes dispatch logic from PropertyWrapperCompute.
Few reasons for this:
- Brings in line with other wrappers which serve only to wrap
- The dispatch is a single line of code and can be done outside
- Resetting state after dispatch means wrapper needs to be re-initd
- Thread group size should in general vary based on shader/workload,
so should not be baked into wrapper
I bumped into these a couple of times on dev branches so thought i should
submit this pr.
Oh i also thought we should move THREAD_GROUP_SIZE_X/Y into LodDataMgr
as i guess logically it can be considered a default value for lod-data related things
(and is paired with constants in OceanLodData.hlsl..).
> Refactor - remove dispatch logic from PropertyWrapperCompute

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanHelpers.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesGerstnerBatchGeometry.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerBatch.shader
- crest/Assets/Crest/Crest/Shaders/OceanLODData.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanLODData.hlsl.meta
- crest/Assets/Crest/Crest/Shaders/OceanSurfaceAlpha.shader
- crest/Assets/Crest/Crest/Shaders/Resources/QueryDisplacements.compute
- crest/Assets/Crest/Crest/Shaders/Resources/QueryFlow.compute
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.compute
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.shader
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateDynWaves.compute
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateFoam.compute
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateShadow.compute
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMeniscus.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterShared.hlsl
Goodbye OceanLODData.hlsl. You won't be missed!
Removes helper functions which relied implicitly on hidden state, and added unnecessary concepts such as the 'bigger'/'smaller' naming. A downside of this is some fairly verbose calling code. A potential fix for this is grouping args in structs.
I think there is more cleanup to follow (OceanHelpersNew -> OceanHelpers?), but thought i'd stop at this point as thats more than enough change for one PR..
> OceanLODData.hlsl removed

- USERGUIDE.md
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/Collision/OceanSampleHeightEvents.cs
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/Collision/OceanSampleHeightEvents.cs.meta
Adds a component that will invoke an event for when the game object changes state from above to below the ocean surface and vice versa.
It can be used to trigger audio and many other things. Pretty versatile and powerful for those who don't know scripting.
> Example height component using UnityEvents

- crest/Assets/Crest/Crest/Shaders/OceanConstants.hlsl
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateShadow.compute
UpdateShadow now uses the shadow term constants from downstream. This works towards making it easier to remove the hard shadow term in HDRP.
> Minor refactor of update shadow

- crest/Assets/Crest/Crest/Materials/OceanInputs/ShadowOverride.mat
- crest/Assets/Crest/Crest/Materials/OceanInputs/ShadowOverride.mat.meta
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs.meta
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ShadowOverride.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ShadowOverride.shader.meta
Adds a shadow input component similar to other LOD data. It could be useful for those who may have edge cases with shadows. The one advantage is complete control as it bypasses jitter.
An example use case is issue #392 where a small enclosed room can appear not shadowed inside because jitter samples outside the walls. 
Fixing the problem by reducing shadow leaks probably won't work because the fixes so far use depth.
> Add shadow input component

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
Don't run queries when in edit mode to stop leaking memory from within the code that creates async gpu readback requests.
Fixes #630
> Fix memory leak

- USERGUIDE.md
- crest/Assets/Crest/Crest/Materials/OceanInputs/FoamOverride.mat
- crest/Assets/Crest/Crest/Materials/OceanInputs/FoamOverride.mat.meta
- crest/Assets/Crest/Crest/Shaders/OceanInputs/FoamOverride.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/FoamOverride.shader.meta
Solves #670 
The same shader as the shadow override but for foam. When used, the input _sets_ the value of the foam data. Can be used to add or remove foam.
> Add foam override to remove foam

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrClipSurface.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
Uses the new GraphicsFormat instead of RenderTextureFormat. GraphicsFormat can handle both textures and render textures. The API is experimental, but is being used in Unity's SRP packages for a while now.
This PR could go further in changing over to the new API for other classes like the OceanDepthCache, but it is probably better to start small and use it for something we really need first.
It also tries to use a format which supports the texture's usage like random access. This should help with #621.
I still need to test this on Windows.
Formats:
[RenderTextureFormat](https://docs.unity3d.com/ScriptReference/RenderTextureFormat.html)
[GraphicsFormat](https://docs.unity3d.com/ScriptReference/Experimental.Rendering.GraphicsFormat.html)
> Use supported GraphicsFormat for LodDataMgr

- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcess.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcessUtils.cs
Use the _ViewCamera_ and _ViewerHeightAboveWater_ properties on the _OceanRenderer_ for underwater effects instead of using the post-processing camera. _ViewCamera_ and the post-processing camera will be the same. Reduces code complexity and saves a height query. This will be merged into HDRP if okay to merge here.
> Use ViewCamera in underwater post-processing

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- crest/Assets/Crest/Crest-Examples/Whirlpool/Scenes/Internal/WhirlpoolSceneCore.prefab
- crest/Assets/Crest/Crest/Scripts/Interaction/SimpleFloatingObject.cs
Approximates hydro dynamics of surfing down a wave. Not physical but helps to compensate for surface motion/flow being unphysical, like in whirlpool scene.
BoatProbes does not have an all-up water normal currently and i didnt end up adding something for it.
I turned this on for the whirlpool scene.
> Option to accelerate some boat types 'downhill'

- crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs.meta
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesGerstnerBatchGeometry.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstner.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstner.shader.meta
- crest/Assets/Crest/Crest/Shaders/Resources/Gerstner.compute
- crest/Assets/Crest/Crest/Shaders/Resources/Gerstner.compute.meta
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.compute
This adds a new, leaner and meaner Gerstner system.
It renders the gerstner waves into a 'wave buffer' that is its own cascade independent of the other lod data, more slices but much lower X&Y res (32x32 by default). The wavelengths are snapped in a way that they always repeat spatially, so that the resulting patch can be tiled on the world XZ plane. Since it tiles, the patches are computed near the origin instead of moving with the viewer, which simplifies a few things.
The wave components are compiled in one list and generating the wave buffer is done in one dispatch. Thanks to this and the low resolution i was measuring <10us for the wave generation time on a 1060 gpu.
By default it does not resample the spectrum each frame in play mode. The gerstner sampling …
> Add new Gerstner system

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanVertHelpers.hlsl
Fix for two issues, both tracked by #665 
**Gaps**: When ocean placed near a regular position (such as an integral boundary or multiple of 0.333333, etc), precision issues related either to how transforms propagate in the unity hierarchy or how the values arrive to the shader mean different tiles can snap to different locations and leave a gap. This adds a slight nudge to push the ocean away from a bunch of common boundaries). The nudge is very small and will not affect the ocean simulation/rendering as everything snaps to much larger values than the nudge. In the future, if gaps appear, it may be the boundary is not on 1/60. The boundary might be lod resolution / lod 0 width. If we get a report of gaps, we should get the camera transform and oceanrenderer …
> Fix gaps and cracks issues

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
When rendering underwater, the ocean surface normals were not being flipped if flow was enabled.
This PR solves it by flipping normals only once after they have been computed. _n_geom_ is not flipped because we don't use it since it becomes _n_pixel_. Easier to just flip them once at the end. Happy to change it so that _n_geom_ is flipped.
> Fix underwater normals not flipped with flow

- USERGUIDE.md
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanShaderHelpers.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanShaderHelpers.hlsl.meta
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
Fixes #426
Adds orthographic projection support. By default the ocean shader supports both orthographic and perspective. But users can choose a mode on the material using a keyword enum to save on performance.
Supporting orthographic projection was just a matter of fixing depth when the camera is orthographic.
I also cleaned up some unused depth references in the shader.
> Orthographic Projection

- README.md
- USERGUIDE.md
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/CopyDepthIntoCache.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/CopyDepthIntoCache.shader.meta
Fixes #158 #371
Based on @huwb's branch: [fix/cache-terrain-depths](https://github.com/crest-ocean/crest/tree/fix/cache-terrain-depths)
Brings over fixes from downstream. Copies depth instead of rendering geometry into ocean depth cache. This didn't work before in 2018 but now works in 2019. Tested on MacOS in build and standalone.
These files are now same as downstream with a few exceptions:
- The copy depth shader use CG instead of HLSL, but they are only a few lines that are different.
- This C# file has a few additional lines which will be added downstream. Allows the depth cache to be used in a prefab
The diff is messy so it is easier to compare these files with the downstream files.
> Fix Terrain "Draw Instanced" not working with Ocean Depth Cache

- crest/Assets/Crest/Crest-Examples/Main/Scenes/main.unity
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodTransform.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesAddFromTex.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesGerstnerBatchGeometry.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/GerstnerShared.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstner.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerBatch.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputsDriven.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanSurfaceAlpha.shader
- crest/Assets/Crest/Crest/Shaders/Resources/Gerstner.compute
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.compute
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.shader
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateFoam.compute
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterShared.hlsl
**Status**: Ready for review. I have arranged these changes into logical commits so reviewing by-commit is a good option.
**Overview**:
Wave variance is statistical measure of how many waves there are in each slice of the displacement cascade. When sampling a low LOD of the waves, there are a lot of small wavelengths missing. The variance is a measure of the cumulative amount of missing content for a given slice. This measure can be used to compensate for the missing data. The killer use case of this is the foam at wave crests - right now we dont get foam at all in the mid-to-background as the pinchy waves are missing from the lower lods. The variance is used to compensate for this missing data and foam is now generated reliably at all LODs.
The variance is stored in the W channel of the …
> Wave variance

- crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.shader
Two changes related to the combine pass..
Firstly, added target pragma which apparently fixes an issue on Quest.
The second changes defaults to not doing ping-pong passes for the combine. The ping pong approach uses a graphics shader and copies results backwards and forwards from an aux RT. This is here because early DX10 GPUs missed a feature we need to run the combine as a compute shader (typed loads). So we added two paths, and defaulted to the "safe" one.
I feel we should change the default to the efficient compute path now, given that the old gpus are something like 15years old now, and see how many people report issues. The symptom is that it silently fails to combine the cascades and the ocean will appear flat. If we don't hear issues perhaps we can consider switching completely …
> Combine changes

- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/EmbeddedFieldAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs.meta
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/EmbeddedAssetHelpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/MultiPropertyDrawer.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/MultiPropertyDrawer.cs.meta
- crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
Open this PR for discussing and merging into #741 and finally into #737
Idea and code taken from:
https://forum.unity.com/threads/drawing-a-field-using-multiple-property-drawers.479377/
Basically allows attribute stacking. Writing the GUI code is a little different as you are not suppose to reset the GUI code so the next attribute in the stack receives the changes. This allows our predicated field and embedded asset field to work together.
I haven't fully evaluated the code yet to see if there are any drawbacks. But everything appears to be working well. It also simplifies the code as we don't need to define our own property drawers.
Usage:
```csharp
[PredicatedField("_createFoamSim", order = 0), EmbeddedField(order = 1)]
public SimSettingsFoam _simSettingsFoam;
```
> Inline settings editing attribute with predicate field support

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
Latest post in issue #665 . This change expands tile epsilon to cover new crack bug. I didnt see any negative side effects of this increased epsilon and it's still quite small. The other repro scenes look fine to me with it as well (tested in editor).
> Expand tile epsilon to cover new crack bug

- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
Fix: #617 (partially)
Fixes an issue where the properties (max terrain height and resolution) on the depth cache or its transform (scale) are changed, the components (camera and textures) are not updated when in the editor when they should be. Users would have to enter and exit play mode which would cause confusion and possibly confusing bug reports. The update method is public so users can call during runtime if they need to change properties on the depth cache.
> Fix: always update cache components in editor

- crest/Assets/Crest/Crest/Scripts/Collision/RayTraceHelper.cs
*_valid* is no longer set to true in *Init* preventing it from running *Trace* fully. I have removed *_valid* completely.
> Fix broken RayTraceHelper

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrClipSurface.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
For each ocean input, checks that feature is enabled on ocean component, and checks that feature is enabled on ocean material.
Hopefully this reduces setup errors.
> Validate if ocean feature enabled, material keyword enabled

- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
Reported by @holdingjason on Discord. The active spectrum isn't set from the serialised spectrum in builds.
> Fix ShapeGerstner breaking in build

- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateFoam.compute
Reported by @woistjadefox in issue #624:
> Tried to make a build but I get these old errors:
> ![image](https://user-images.githubusercontent.com/58563011/96013237-5108de00-0e45-11eb-8eb5-341ca42873b8.png)
> [editor_error_log.txt](https://github.com/crest-ocean/crest/files/5379376/editor_error_log.txt)
> 
> I think this happend in a version before already. Should I just switch all half3 and half2 to float3 / float2 in the underwater shader for testing reasons?
Not sure if I got them all. Some of these might be URP specific so I will have to do a pass there too. This also includes a fix for the determinant wanting float4 for PSSL which was reported on Discord.
@woistjadefox If you could test this branch and let me know if you see any more errors and I will try and fix them here.
> Fix PSSL/PS4 shader errors

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
Adds a material editor similar to what the mesh renderers get. The only difference is that this appears right after the component rather than after all other components.
I wasn't able to make the feature an attribute like the SO editor. This is more difficult as the foldout should appear after the component at the very least. It is probably possible but will require more engineering than the other.
> Add embedded material editor to OceanRenderer

- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
Adds a "fix" button (similar to the jump button) to solve validation issues.
#767 is a really good case for this which I have provided as a test commit. It will migrate the layer names to the layer mask for the user.
Implementation was a lot simpler than anticipated too which is nice.
I have also added a fix for the jump button. *Selection.activeObject* could be the GO which isn't what we pass through (we pass "this" which is the component). Alternatively, it could be fixed by always passing the GO but the current fix covers both cases.
The icon was chosen from the following [list of icons](https://github.com/halak/unity-editor-icons). I couldn't find a suitable fix or repair icon.
> Add inline button to fix validation issues

- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/EmbeddedFieldAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/MultiPropertyDrawer.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs
I forgot to handle the case where the PredicatedFieldAttribute is the only MultiPropertyAttribute and needs to call EditorGUI.PropertyField. The way the system works is that the last MultiPropertyAttribute handles rendering. This wasn't a problem with the embedded attributes because they handled the call and the PredicatedFieldAttribute only "decorated".
> Fix PredicatedFieldAttribute not rendering

- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesGerstnerBatchGeometry.shader
This creates a feedback loop of doom and is making the patch of waves in boat.unity flicker for me.
> Don't let gerstner waves shader sample displacement

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrClipSurface.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
Shader keywords differ with SG. They either have a prefix or are missing. The point of this PR is to reduce diff noise and increase compatibility. Hopefully, this will be a temporary solution.
Adds a *MATERIAL_KEYWORD_PREFIX* constant which is used:
```csharp
internal const string MATERIAL_KEYWORD = MATERIAL_KEYWORD_PREFIX + "_FOAM_ON";
```
For built-in, the prefix is an empty string, but CREST_ will be added in HDRP (diff noise).
MATERIAL_KEYWORD_PROPERTY
The next is skipping any keyword where the *OceanMaterial.HasProperty* is false. This checks the property name. So for foam we check "_Foam" which matches with "FOAM_ON".
So with SG, if we do not have a keyword defined, then it will be skipped.
*MATERIAL_KEYWORD_PROPERTY* has been added which will need to be changed in HDRP (diff …
> Make shader keyword check compatible with Shader Graph shader

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
It has been reported that VFACE is causing issues on the latest consoles.
According to [Microsoft documentation about VFACE](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-semantics#semantics-supported-only-for-direct3d-10-and-newer):
> This semantic is available in Direct3D 9 Shader Model 3.0. For Direct3D 10 and later, use SV_IsFrontFace instead.
> Change VFACE to SV_IsFrontFace

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
Makes it similar to shader graph. It will help with documentation and referencing.
I chose the names from HDRP where they matched.
I also made two new sections: _Shallow Scattering_ and _Foam Bubbles_. Breaks up the documentation better with these additional headings and properly groups foam bubbles settings together.
> Rearrange and rename ocean material properties

- README.md
- USERGUIDE.md
- crest/Assets/Crest/Crest-Examples/Main/Scenes/Internal/MainSceneCore.prefab
- crest/Assets/Crest/Crest/Scripts/Helpers/AssignLayer.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/EditorHelpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/WindowCrestWaterBody.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/ProjectSettings/TagManager.asset
Fixes #752 
- Marks *Assign Layer* component as *Obsolete*
- Marks *Layer Names* component as *Obsolete* and hides in inspector
- Adds Layers property (LayerMask)
- Adds fix button in validation to help users migrate
- Sets *Terrain* layer in main scene prefab (some extra data in the diff, sorry)
- Removes *Assign Layer* component from main scene
- Updates documentation
Terrain layer will not exist when importing Crest, but this is fine since it will still work. Since we are setting it in the main scene, I believe there will be no conflicts.
If users access the _layerNames in scripting, they'll see a warning. And the AssignLayer component will have a warning help box.
> Deprecate AssignLayer. Use LayerMask for depth cache

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
Helps with underwater when camera is reasonable (lack of better word) distance from zero. Nothing really solves underwater issues at larger distances though, but the gap fix does work well for above water.
If we find that this is going to be permanent, then we could script the lerp value to save performance cost.
> Scale gap fix by camera position

- crest/Assets/Crest/Crest/Scripts/Helpers/AssignLayer.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/FloatingObjectBase.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrClipSurface.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Scripts/Spline/Spline.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
- docs/about/history.rst
I realised when clicking the fix button on the depth cache layers validation that its useful to know what the fix will do.
This PR adds a 'mode' to the fix function where it describes the fix action, so the user knows what will change.
Also adds a fix action for material keyword not set, and for dynamic waves disabled errors.
> Validation fix descriptions to describe fix to user

- crest/Assets/Crest/Crest/Scripts/Constants.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsWave.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Scripts/Spline/Spline.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
- docs/README.md
- docs/about/history.rst
Adds the version and render pipeline to the help URLs.
Currently, it points to 4.10 which doesn't exist yet. A custom 404 page will redirect users to latest until the 4.10 tag is published. This allows us to change the version once (after publishing a tag). Otherwise, we would have to change it from latest to 4.10, and then back to latest.
The constants are tedious looking, but this can be fixed with a custom help URL attribute similar to [Unity's](https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.render-pipelines.core/Runtime/Documentation.cs). We cannot do this now as the HelpURLAttribute is sealed. But it must of been unsealed in 2021 or later.
> Add version and RP to HelpURL

- crest/Assets/Crest/Crest/Scripts/Crest.asmdef
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
Will help with #801
Validates both _Animated Materials_ and _Post-Processing_ options under the scene view effects menu. The former option is an information help box and the latter is a warning help box. Furthermore, the latter is only validated in built-in and if the main camera has an active layer (ie only validate when the bug occurs). See code for help box copy.
> Validate scene view effects options

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/Collision/OceanSampleDisplacementDemo.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/EmbeddedFieldAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/MultiPropertyDrawer.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterHeightInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Development/Editor/AttributeValidator.cs
- crest/Assets/Development/Editor/AttributeValidator.cs.meta
- crest/Assets/Development/Editor/Crest.Development.Editor.asmdef
- docs/about/history.rst
- Fixes embedded field attribute for 2021
- Nicer architecture
- Added range and delay fields that work with predicated
- More robust and possibly performs better (untested)
Unity changed something in 2021 causing the _MultiPropertyDrawer_ to be called twice when a property had two attributes that inherited from _MultiPropertyAttribute_ and one of those called _EditorGUI.PropertyField_ (looking at you _Embedded_).
The fix was to separate _MultiPropertyAttribute_ into decorators and decorated attributes. A property will have only one decorated field which solves the problem of targeting multiple attributes.
_PredicatedField_ has been changed to _Predicated_ and is now a decorator. It cannot be used by itself as decorators do not call _EditorGUI.PropertyField_ so  I have added a general …
> Rewrite multi-property attributes as decorated/decorator attributes

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanNormalMapping.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanShaderData.hlsl
- docs/about/history.rst
- docs/user/configuration.rst
- docs/user/includes/_hdrp-reflections.rst
A couple of previous support issues would have been helped by having an overall normal strength control for the water surface which this PR adds.
Also wrapped up in these changes - there were unnecessary normalize() calls and other cleanup to do for the pixel normal calculation. This change moves to surface gradient style setup - derivatives are added/scaled, then normalize happens once at the end of the calculation.
> Use surface gradients and add overall normal scale

- crest/Assets/Crest/Crest-Examples/Crest.Examples.asmdef
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/CamController.cs
- crest/Assets/Crest/Crest/Scripts/Crest.asmdef
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- docs/about/history.rst
Xbox throws build errors here in more recent Unity versions according to reports. Easiest way to develop guards against this is to just disable the VR and/or XR modules.
> Fix build errors for platforms without XR/VR support

- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- crest/Assets/Crest/Crest/Shaders/Resources/QueryDisplacements.compute
- crest/Assets/Crest/Crest/Shaders/Resources/QueryFlow.compute
Potential fix for bugs where a large boat may stop moving when camera is close.
Last LOD is used for transitioning waves across resolutions to avoid pops and is not suitable for use in queries.
I have moderate confidence this won't create other knockons but let me know if you can think of potential issues.
> Don't let queries use last LOD

- docs/.gitignore
- docs/_static/custom.css
- docs/_static/custom.js
- docs/_templates/sidebar/brand.html
- docs/about/introduction.rst
- docs/about/roadmap.rst
- docs/conf.py
- docs/extensions/sponsor.py
- docs/extensions/trello.py
- docs/index.rst
- docs/user/collision-shape-for-physics.rst
- docs/user/includes/_birp-lighting.rst
- docs/user/includes/_birp-shadows.rst
- docs/user/includes/_urp-lighting.rst
- docs/user/other-features.rst
Adds a sponsor admonition which can be used to highlight features which would need expanded sponsorship to be worked on. Also adds the roadmap with Trello embeds.  
Here are the links for affected sections:
- https://crest.readthedocs.io/en/docs-sponsorship-and-roadmap/about/introduction.html#sponsorship
- https://crest.readthedocs.io/en/docs-sponsorship-and-roadmap/about/roadmap.html
- https://crest.readthedocs.io/en/docs-sponsorship-and-roadmap/user/configuration.html#lighting
- https://crest.readthedocs.io/en/docs-sponsorship-and-roadmap/user/ocean-simulation.html#shadows
- https://crest.readthedocs.io/en/docs-sponsorship-and-roadmap/user/collision-shape-for-physics.html#compute-shape-queries
- sidebar has the sponsor button below the logo
Let me know what you think. Wording could be …
> Docs: Add sponsorship and roadmap

- crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
To support servers, we need to run fine when `-nographics` is given as a commandline option, and when `-batchmode` is given as a commandline option. We also need to avoid unnecessary work in both.
To run a server instance, run the following from the command line
`CrestBuild.exe -batchmode -nographics -logfile log.log`
I have added two toggles that emulate batch mode and emulate running without a GPU on the OceanRenderer component.
* Does not construct a surface mesh
* Only creates sims required for queries, like wave sim
In addition to `batchmode`:
* Does not create any loddata
* Errors if other GPU-dependant features are used, like runtime baking of depth caches
> Server support

- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
Unity has an internal PowerSlider. So I just grabbed it with reflection. It should be safe to use as I found it in the [C# reference](https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/EditorGUI.cs#L2438) which is for 2020.2. Also, [materials have a PowerSlider attribute](https://docs.unity3d.com/2021.2/Documentation/ScriptReference/MaterialPropertyDrawer.html) available which I believe uses this method too.
I have set the power to 2 for wind speed. I find higher values like 3 has a dead zone at the start. Let me know if you want it changed.
> Add power to range attribute

- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
- docs/about/history.rst
The wind speed should no longer be baked into the spectrum. The spectrum should give the character of the ocean for any wind speed, and the wind speed is applied based on current wind conditions dynamically.
I removed the wind speed from the analytical spectra which seemed to work.
While doing so i found the 'small wave multiplier' is only really needed for JONSWAP, and have an effect akin to simple scaling for the otehr spectra. Given we already have a multiplier param on the spectrum, its useless and another param that users have to grapple with. I got good results removing params from phillips/moskowitz by tweaking a good default value, and the parameter ranges for jonswap look good now too.
Most of the jonswap tweaking range is exponentially distributed at the low end, so i made the …
> Remove wind speed from analytical spectra, and generally tweak

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- docs/about/history.rst
Only affects URP when _Enable GPU Instancing_ is enabled. Since _UNITY_MATRIX_M_ is the same as _unity_ObjectToWorld_, and we use it already in _SnapAndTransitionVertLayout_, it is a no brainer to apply the fix in built-in.
What was happening was the gap fix was pushing tiles away from camera. Must be a bug with URP.
> Fix ocean tiles moving away from camera when far from zero

- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrClipSurface.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- docs/about/history.rst
When a simulation was disabled, null textures weren't being bound for shaders. I have also removed some unnecessary bind calls. I have separated everything by commit. Let me know what you think.
> Fix null texture bindings

- docs/about/history.rst
- docs/index.rst
- docs/user/configuration.rst
- docs/user/faq.rst
- docs/user/includes/_birp-reflections.rst
- docs/user/includes/_hdrp-reflections.rst
- docs/user/includes/_urp-reflections.rst
- docs/user/rendering.rst
- docs/user/technical-information.rst
- docs/user/underwater.rst
I wanted to add issues with refractive materials after someone asking about the issue with HDRP. I also improved other areas too.
- Add [rendering](https://crest.readthedocs.io/en/docs-rendering-page/user/rendering.html) page which covers transparent material issues
- Updated FAQ questions to refer to said page
- Add refractions section to configuration page
- Nested reflections and refractions under [lighting](https://crest.readthedocs.io/en/docs-rendering-page/user/configuration.html#lighting) heading
- Moved "render order" section to rendering page
Let em know if you can think of any improvements.
> Docs: add Rendering page. Improve lighting

- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
This is to be merged into #650.
I had this in my stash. I tested with two ocean instances and two cameras. Appears to work. I have added test data with two camera setup.
> Multiple Oceans: Connect underwater to ocean instance

- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
- docs/about/history.rst
Fixed a bad merge which resulted in the "remove mesh renderer" help box not showing when it should be. Also fixes an exception because we pass in either a component or GO to some of the fix functions.
> Fix "fix" helper exception and fix help box not showing

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
From a support request - allow setting ocean material from code.
Changing it at runtime works for me so i think it was probably just waiting for the request ot make it public.
(It was slightly tempting to make the setter apply to all tiles, rather than have the tiles poll the material many times pre frame, but that should probably be a separate change).
> Allow set ocean mat

- crest/Assets/Crest/Crest/Scripts/Helpers/CrestSortedList.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
The spectrum part of the debug GUI doesn't take component enabled/disabled into account. I went with the simplest and lowest overhead route of just having a static list on both ShapeGerstners. Only downsides are that there is an overhead (negligible I think) even if OceanDebugGUI is not used.
In 2020 *FindObjectsOfType* can exclude inactive objects, but we would still have to call this every frame or implement on hierarchy change event if we wanted this to be dynamic. But may be worth it.
> Only show enabled spectrums in debug GUI

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Scripts/Time/TimeProviderCustom.cs
- crest/Assets/Crest/Crest/Scripts/Time/TimeProviderCutscene.cs
- crest/Assets/Crest/Crest/Scripts/Time/TimeProviderCutscene.cs.meta
- crest/Assets/Crest/Crest/Scripts/Time/TimeProviderNetworked.cs
- crest/Assets/Crest/Crest/Scripts/Time/TimeProviderNetworked.cs.meta
- docs/about/history.rst
- docs/user/other-features.rst
**Cutscene Time Provider**
A time provider that `OnEnable` registers itself and drives the Timeline time into the system. `OnDisable` it unregisters itself so cutscenes can be loaded/unloaded on the fly.
To make this push/pop of TPs work elegantly, the runtime TP storage is a list that behaves loosely as a stack. Pushing a TP always moves it to the top of the stack, and popping a TP removes it from anywhere in the stack. This way TPs always activate when they are pushed, and when removed the system has a memory of the previous TP to fallback to. This applies to user-assigned TPs as well.
**Networked Time Provider**
After years of assuming this was a complicated thing, i've realised this probably just needs a time provider with a configurable offset, so just a few lines of code.
**Custom …
> Cutscene and Networked Time Providers

- crest/Assets/Crest/Crest/Scripts/Helpers/Hashy.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
While working on something else and attempting to hash an object instance ID, i found it converting an object ref to a bool (i guess doing an 'is null' operation' and calling `Add(bool)`, and failing to hash properly (!?). Wow.
Rather unfortunate but i could not find an elegant way in C# to avoid implicit conversions. I did find i could pass the first arg to `Add()` by reference, which may sort it, however passing stuff in by reference is probably hackier than doing this.
> Make hashy functions type explicit

- crest/Assets/Crest/Crest-Examples/BoatDev/Scenes/Internal/BoatSceneCore.prefab
- crest/Assets/Crest/Crest-Examples/BoatDev/Scenes/Internal/ThreeBoatsSceneCore.prefab
- crest/Assets/Crest/Crest-Examples/Main/Scenes/Internal/MainSceneCore.prefab
- crest/Assets/Crest/Crest-Examples/Whirlpool/Scenes/Internal/WhirlpoolSceneCore.prefab
- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/EmbeddedFieldAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/HelpBoxAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/HelpBoxAttribute.cs.meta
- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/LayerAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/LayerAttribute.cs.meta
- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/MultiPropertyDrawer.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs
- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
- crest/Assets/Development/Editor/AttributeValidator.cs
- crest/Assets/Development/Scenes/Internal/TestScene.prefab
- docs/about/history.rst
Deprecates the _Layer Name_ and adds _Layer_ to supersede it. Since a lot of people are going to hit this, I put a fair bit of effort in making sure the transition is as smooth as possible. This should make things easier in the future.
I have groups changes into commits for easier digestion. Notable changes are:
- Predicated now works with strings
- Add call-to-action (eg "Click fix button") to help box message
- Add Layer attribute
- Add HelpBox attribute (it uses predicated to show/hide itself)
- Deprecated layer name. It will still be used if data is there
- Add Layer. Cannot be used until migrated
The plan is that in some future version we just remove the Layer Name and ignore the old data. By that time hopefully enough people have migrated.
I have left our scenes alone for …
> Replace Layer Names with Layer enum

- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- docs/about/history.rst
Have no idea why this was set globally instead of per-material.
> Fix bug where all ShapeGerstners used one wind heading

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/BoatProbes.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SimpleFloatingObject.cs
- docs/about/history.rst
Made many fields public for *BoatProbes*, *BoatAlignNormal* and *SimpleFloatingObject*. I went through and made sure they were safe to make public (no state relied on them in Start etc).
> Make fields public for floaty things

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- crest/Assets/Crest/Crest-Examples/Crest.Examples.asmdef
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/CamController.cs
- crest/Assets/Crest/Crest/Scripts/Crest.asmdef
- crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
Can probably be cleaned up more using variables, but for now a straight drop-in replacement around input code that shouldn't impact existing functionality.
> Use InputSystem when enabled in build settings

- crest/Assets/Crest/Crest/Materials/Ocean-Underwater.mat
Copies over the colours, specular and depth fog density from URP so they are similar. I also changed IOR of air to 1 since it is deprecated.
@huwb Did you want the other ocean material to have the same values?
> Update ocean underwater material colours

- crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT.meta
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs.meta
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs.meta
- crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Shaders/Resources/Debug/TextureArray.shader
- crest/Assets/Crest/Crest/Shaders/Resources/FFT.meta
- crest/Assets/Crest/Crest/Shaders/Resources/FFT/FFTCompute.compute
- crest/Assets/Crest/Crest/Shaders/Resources/FFT/FFTCompute.compute.meta
- crest/Assets/Crest/Crest/Shaders/Resources/FFT/FFTSpectrum.compute
- crest/Assets/Crest/Crest/Shaders/Resources/FFT/FFTSpectrum.compute.meta
- docs/about/history.rst
- docs/about/known-issues.rst
- docs/user/wave-conditions.rst
**Status**: This is a transfer over from our private repos and is ready to merge from my POV
* Adds multi-scale FFT. Wave generation in this setup takes 28us on my 1060
* Generalises debug gui texture view to allow drawing any texture array
* Generalise debug gui texture view to allow scale/bias to data. Useful when data can go negative, or has a large or small range
* Supports spectrum control over FFT. Further, Pierson Moskowitz was used to calibrate our gerstner spectrum with the same spectrum using FFT.
* The calibration changed the gerstner spectrum. I've introduced a new pattern for migrating the spectrum data.
**Testing**:
Add ShapeFFT to a GameObject in the scene and it will add FFT waves.
> Add FFT waves

- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/CopyDepthIntoCache.shader
Fixes compile error building standalone development build in win64, 2020.3.10.
Trivial change, but i have no idea why I hit this in years-old code.
> Fix compile error building win64 player

- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
Right now, if N wave splines are used with some spectrum `Spectrum A`, the FFT will be run N times. The wave gen happens in a 'canonical' frame and if wind dir, speed etc are the same, the result will always be the same, so we should only generate the waves once in this case. I think we should allow many splines to be placed, so I think we should pursue this optimisation.
This is a preparation commit - it makes `FFTCompute` return the wave data.
The next step will be to make the `GenerateDisplacements` function static, and have it hash the input arguments and use that as a key into a generator dictionary. It can then return the data from the right generator. This PR moves the data into the generator as a first step.
> Make FFTCompute own its generated data

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
Fixes #812 
`VerifyRequirements` only relevant/valid for runtime to check target platform, not for a build machine/environment.
> Don't verify reqs for builds

- docs/about/history.rst
- docs/conf.py
- docs/user/rendering.rst
- docs/user/underwater.rst
Rearranges and rewrites a few things for the _Underwater Renderer_ being the primary underwater solution.
- Added _Underwater Renderer_ to underwater page
- Deprecated curtain and post-processing
- Changed underwater transparents for _Underwater Renderer_
- Added release notes
Here are the pages:
https://crest.readthedocs.io/en/docs-underwater-renderer/user/underwater.html
https://crest.readthedocs.io/en/docs-underwater-renderer/user/rendering.html
https://crest.readthedocs.io/en/docs-underwater-renderer/about/history.html
> Document Underwater Renderer

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterHeightInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsBase.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
- docs/user/ocean-simulation.rst
Fixes #864
- Refactors settings code to push code up to LodDataMgr
- Can now add settings from SimSettings to settings hash (only needed for changing textures so far I believe)
- Adds texture format option for animated waves to solve precision issues
- Adds validation to height input to warn users if not using higher precision texture
- only really useful if they are using the default
- Documents animate waves settings and links to it
> Add texture format setting to fix precision issues from height input

- crest/Assets/Crest/Crest/Shaders/Resources/FFT/FFTSpectrum.compute
- docs/about/history.rst
Fixes #856. My guess was that file-level variables cannot be manipulated on Game Core platforms. I haven't confirmed this solves the problem though. FFTs look like they are working as before.
> Fix FFT Game Core shader compile errors

- crest/Assets/Crest/Crest/Scripts/LodData/LodTransform.cs
- docs/about/history.rst
Helps solve #865
Current the LOD data is rendered from a position of 100m above sea level. I have had reports of people setting the height above this position. So this adds a setting to allow them to change both above and below rendering bounds.
Not sure if you planned on solving this some other way with water bodies, but this seems like an okay solution for now. Let me know what you think.
Will add documentation if solution seems good.
> Add LOD data matrix height options

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- docs/about/history.rst
Flow, ~~clip and depth~~ simulations where not being cleared when the last input is disabled.
> Fix disabled input not being cleared if last one

- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- docs/about/history.rst
Reported to me on Discord (I think) that FFT was creating a material every frame. Fixed it by caching the two material options.
> Fix FFT material allocations every frame

- crest/Assets/Crest/Crest-Examples/BoatDev/Models/OldBoat/RowBoat.prefab
- crest/Assets/Crest/Crest-Examples/BoatDev/Scenes/Internal/BoatSceneCore.prefab
- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrClipSurface.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsClipSurface.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsClipSurface.cs.meta
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ClipSurfaceSignedDistance.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ClipSurfaceSignedDistance.shader.meta
- docs/about/history.rst
- docs/user/ocean-simulation.rst
Adds signed distance shapes (Sphere and Box) to the clip surface input. It uses the clip surface input transform to define the shape. It renders the quad using DrawMesh. It gets the material from the mesh renderer.
The only issue is the corners of the box can get cut off or rounded:
The PR has a few commits which adds test data which I can remove before code review.
I considered moving away from using a mesh renderer and using DrawMesh for all inputs. But I didn't want it to hold this up as that is a significant refactor when including migration code.
I was thinking of adding the shape type to the component itself and driving the shape keywords with scripting. Thoughts?
- Blending doesn't work on my old Mac but probably because it is old
> Add signed distance clip surface shader

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/Ocean.shader.meta
- docs/about/history.rst
Adds default textures to shader. Also updates the shader default values based on current material and URP. So now when creating a new ocean material it looks similar to the ocean material we provide.
> Add default textures to ocean shader. Update other defaults

- crest/Assets/Crest/Crest-Examples/Shared/WaveSpectra/WavesBoatScene.asset
- crest/Assets/Crest/Crest-Examples/Shared/WaveSpectra/WavesCalm.asset
- crest/Assets/Crest/Crest-Examples/Shared/WaveSpectra/WavesDead.asset
- crest/Assets/Crest/Crest-Examples/Shared/WaveSpectra/WavesModerate.asset
- crest/Assets/Crest/Crest-Examples/Shared/WaveSpectra/WavesModerateSmooth.asset
- crest/Assets/Crest/Crest-Examples/Shared/WaveSpectra/WavesShoreline.asset
- crest/Assets/Crest/Crest-Examples/Whirlpool/Data/WavesWhirlpool.asset
I occasionally get the "big waves" issue when reverting the wave assets, so i thought we should just bake in the version number which should sort it (seems to work for me).
> Upgrade spectrums to fix "big wave" issue when reverted

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- docs/about/history.rst
Solves #671 and should help with #635.
Samples foam from the fragment shader. The difference is quite significant from a distance.
Vertex (Current):
Fragment:
Shoreline foam is greatly improved and the foam bubbles is no longer pixelated.
The foam bubbles could also be solved using a higher mesh density, but those screenshots already have a decent mesh density (384 resolution / 4 down sample). And adjusting the texture scale can produce passable results.
I have added it as a toggle/keyword for comparison. We could keep it optional. I've moved the camera in the main scene for testing.
Also, this won't look correct with ShapeGerstner or ShapeFFT because of #878. It makes the lines more prominent.
@huwb Let me know what you think.
> Sample foam in fragment shader

- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- crest/Assets/Crest/Crest/Shaders/OceanConstants.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterEffect.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterMaskHorizon.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterMaskHorizon.shader.meta
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectShared.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMaskShared.hlsl
- docs/about/history.rst
Replaces C# horizon line code with a horizon line shader. It renders a quad near the far plane and compares the world position against the ocean level. It passed the test cases I had available and solved a few edge cases.
PR also includes meniscus fixes/improvements.
Fixes the following edge cases:
- inverted horizon normal at certain camera transforms
- horizon instability when VR hardware is nearly aligned with horizon (last chapter of [video](https://www.youtube.com/watch?v=pGFjiWDinK0))
Measuring the cost of the horizon shader. Measurements taken for the entire mask pass.
No waves and aligned with horizon (worst case scenario)
Old mask: 0.04ms
New mask: 0.14ms
Waves
Old mask: 0.11ms
New mask: 0.11ms
I haven't experienced any. Will have to do some more testing with clip surface and …
> Render underwater horizon into mask

- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs.meta
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanGlobals.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanShaderData.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanShaderHelpers.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterEffect.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectShared.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMaskShared.hlsl
- docs/about/history.rst
Related Issues: #800 #529
Searches for the maximum depth value. It adds four additional samples for the ocean renderer and four additional samples for the underwater renderer. The end result is a dark edge around objects instead of a light edge which is preferable.
Without Fix
With Fix
The offset amount is driven by scripting as it needs to be "2" for HDRP if refraction is used; otherwise, the issue will reoccur. I cannot work out why this is a problem for HDRP and not BIRP.
HDRP refraction with 1 offset (gets worse with higher refraction)
HDRP refraction with 2 offset
The approach fails in certain situations where objects are close together:
There is a way to sample from the MSAA depth texture for HDRP which produces perfect results, but the texture is not accessible if Render Graph is …
> Support MSAA

- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- docs/about/history.rst
It gets reported every so often that the _Ocean Depth Cache_ disables itself in edit mode. There is no hard requirement on an _Ocean Renderer_ being present so I have removed the check. I have added validation to notify users of the considerations.
> Fix Ocean Depth Cache disabling itself in edit mode

- crest/Assets/Crest/Crest/Scripts/LodData/RegisterHeightInput.cs
- docs/about/history.rst
Helps solve #865
Reports the renderer bounds on Animated Waves input by default. The reasoning is that I think reporting the renderer bounds requires some understanding of the system which most will not know. They may come across this issue and not understand the cause. This is a "working correctly by default and optimisation yourself" approach. Let me know what you think.
> Report renderer bounds by default for Animated Waves input

- crest/Assets/Crest/Crest/Shaders/Resources/UpdateDynWaves.compute
- docs/about/history.rst
Adds reflections from the ocean depth cache for dynamic waves.
The attenuation formula applied to dynamic waves is not strong so in its current state most dynamic waves pass through zero depth values. This PR just makes the depth cache absolute when at zero which results in a reflection. Some still pass through (especially if zero depth is thin).
https://user-images.githubusercontent.com/5249806/132119168-13b1bf7b-b37f-40a9-a396-c74a09b87471.mov
Without reflections
<br>
https://user-images.githubusercontent.com/5249806/132120099-0b24e1cb-53f0-40b1-9976-b386fd0b9f5f.mov
With reflections
<br>
> Add dynamic waves depth cache reflections

- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ClipSurfaceConvexHull.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/ClipSurfaceSignedDistance.shader
- docs/about/history.rst
Adds an "inverted" option to both SDF and convex hull clip surface inputs. Both of these can now remove clip surface data.
With the new order property for SDF, one can create some interesting patterns:
Left: Convex Hull. Right: SDFs
> Clip surface input inverted option

- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
- docs/about/history.rst
- docs/user/water-bodies.rst
**Status:** Ready for review
In response to a support request - add a material override field to water bodies. Seems to work fairly straightforwardly (IMO).
> Water body material override

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/GerstnerShared.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstner.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerGeometry.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/CopyDepthIntoCache.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepths.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCache.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputsDriven.hlsl
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateDynWaves.compute
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateFoam.compute
- docs/user/ocean-simulation.rst
This stores terrain height into the depth data.
This is roughly equivalent to storing water depth, but is more general. It will make things simpler when the water level can vary for lakes and rivers. For example populating a depth cache for a river where water level varies is complicated, as the generation needs to know the water level. With this change, the depth cache just stores terrain height which is simple.
Anything that needs the water depth now calculates it as the difference between the sea level and the terrain height. The local water bodies branch will add another channel to this texture to store the sea level, so the calculation will eventually subtract the two channels rather than using the global sea level.
I searched all usages of …
> Store terrain height instead of computing water depth

- crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodTransform.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Shaders/OceanGlobals.hlsl
- crest/Assets/Crest/Crest/Shaders/Resources/FFT/FFTSpectrum.compute
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateDynWaves.compute
**Status**: Seems to work here but could use second pair of eyes
I think this fixes both the lines in foam #878 , and also recently asked question on discord about quality of a single band of FFT waves (by gamemachine i think).
Using 2 samples per wave in FFT is too low. This uses 4 samples per wave instead.
It seems like this fixes the lines in foam, which seem to have been down to bad quality of wave displacements. There are still repeating patterns in foam which is to be expected, but not obvious lines.
Also the Texels Per Wave param on the OceanRenderer component seems to need to be set to 2 for best results. I dont think this param is a good user facing feature, so I've committed to removing it to clean up the UI and hardcode what i feel should be a system var (and hard code it to …
> Make FFT use 4 samples per wave (min), not 2

- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- docs/about/history.rst
I was calculating this twice. Also, removes this code path from SRP as the IVP matrix is provided by Unity.
> Remove duplicate matrix calculation

- crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
- docs/about/history.rst
When "Project Settings > Texture Quality" is not "Full Res" our black texture array becomes white (probably junk). This is a bug with _Graphics.CopyTexture_ when using texture arrays. This can happen in builds when quality settings may be different (ie high in editor or low in build) than in editor which can be hard to debug.
Workaround is to set [_QualitySettings.masterTextureLimit_](https://docs.unity3d.com/ScriptReference/QualitySettings-masterTextureLimit.html) to zero before calling _Graphics.CopyTexture_. I have seen others do this for other bugs for this same method. We can also use SetPixels instead but this looks good enough. I have submitted a bug report to Unity for texture arrays.
> Fix white texture when sims are disabled with texture quality below full resolution (workaround)

- crest/Assets/Crest/Crest/Scripts/Editor/ObsoleteShaderGUI.cs
- crest/Assets/Crest/Crest/Scripts/Editor/ObsoleteShaderGUI.cs.meta
Adds a custom ShaderGUI for obsolete shaders.
Example usage:
```shader
Shader "Crest/Inputs/Animated Waves/Set Base Water Height Using Geometry"
{
Properties
{
[HideInInspector] _ObsoleteMessage("Use <i>Crest/Inputs/Sea Floor Depth/Set Base Water Height Using Geometry</i> instead.", Float) = 0
// ...
}
// ...
CustomEditor "Crest.ObsoleteShaderGUI"
}
```
> Add ObsoleteShaderGUI

- crest/Assets/Crest/Crest/Scripts/Editor/BuildProcessor.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterEffect.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterMask.shader
- docs/about/history.rst
I made a mistake with stripping as I was not stripping variants for the "__" (ie no keyword) case. It was reported on discord that underwater shader was using ~500mb. It is now under 25mb which puts it in line with other shaders.
> Fix underwater high CPU memory usage

- crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs
- docs/about/history.rst
This was an edge case that I missed. If ShapeFFT is enabled in play mode in the editor with a default spectrum, then it will not get the version upgrade it needs.
The fix was to also call the upgrade code in Awake in the editor.
> Fix default spectrum breaking in editor when enabled in play mode for ShapeFFT

- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs
- docs/about/history.rst
This is just a quick fix. Downside is that it runs at full rate instead of editor update intervals. Alternatives could be to add a CurrentUnscaledTime similar to CurrentTime. Or to hash the spectrum.
> Fix FFTs not updating with spectrum changes when paused

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanConstants.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- docs/about/history.rst
The extents have no SSS factor resulting in popping and extents being noticeably different.
Extents can be seen in the right view.
Solved by setting SSS factor to 0.5 at last LOD.
> Fix no SSS value at extents

- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/CrestFillMaskArtefacts.compute
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/CrestFillMaskArtefacts.compute.meta
- docs/about/history.rst
Fixes #739
Uses a compute shader to fill specks visible when underwater due to ocean surface precision issues and other imperfections producing incorrect mask values. Incorrect values can be incorrectly flipped VFACE and/or gaps in the ocean surface.
Samples both orthogonal and diagonal pixels separately. If the sampled pixels are all equal, then it writes that value to the current pixel. Sampling both orthogonal and diagonal is necessary for when a chain of incorrect values is in the mask which is possible.
S = current pixel. 1-4 is checked pixels.
On a 1660Ti at 4K, GPU performance cost was 0.31ms. This cost appears to be consistent.
This shader won't work on old macs as it doesn't like read and write to RWTexture2D for some reason (which is also why I think combine compute shader …
> Fix visible specks underwater

- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- docs/about/history.rst
Negative values were being clamped due to compression which I have disabled. I also disabled NPOT Scale which slightly changed values on import.
> Fix depth cache incorrectly importing 4.14 baked depth caches

- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
- docs/about/history.rst
Report on:
_Dell Inspiron 3537_
processor: CPU: Intel (R) Core (TM) i7-4500U CPU @ 1.80GHz [4 cores]
graphics_memory: VRAM: 2216MB. Max texture size: 16384px. Shader level: 50
Version: Direct3D 11.0 [level 11.0]
Renderer: Intel (R) HD Graphics Family VRAM: 2216 MB
_MacBook Pro_ (mine)
Intel iGPU
It looks like UAV Read/Write is patchy which I believe is also the problem with the combine compute shader. There isn't a great way to detect this as I thought `SystemInfo.IsFormatSupported(GraphicsFormat, FormatUsage.LoadStore)` is the correct check but it passes in this case. Going by the _Graphics_ repository there are specific checks for Intel so this is in line with Unity. I have reported it to Unity a while ago and see what they say.
> Fix underwater specks for Intel iGPUs

- crest/Assets/Crest/Crest-Examples/Shared/Scripts/UnderwaterEnvironmentalLighting.cs
- crest/Assets/Crest/Crest-Examples/Shared/Scripts/UnderwaterEnvironmentalLighting.cs.meta
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs.meta
- docs/about/history.rst
- docs/user/underwater.rst
It very often requested to reduce the depth fog only for the underwater effect. This adds a 0 (0.01) to 1 factor for the underwater fog. I don't think we need to go above 1.
> Underwater fog multiplier

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- docs/about/history.rst
An issue with clip surface not being accurate for large waves was reported and I discovered it was blowing out when there was horizontal displacement. Uncertain if it is the reported issue.
Blowout of the sphere which is clamped sample due to incorrect slice index.
Fixed.
> Fix clip surface using incorrect slices

- crest/Assets/Crest/Crest/Shaders/ShaderLibrary/UpdateShadow.hlsl
- docs/about/history.rst
Uses the displaced position in UpdateShadow to sample the shadow maps to improve shoreline (and elsewhere) shadowing. The improvement is less noticeable in HDRP as we don't use the shadow data for specular shadows. But improves SSS shadowing for every RP.
> Use displaced position when sampling shadow maps

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsWave.cs
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateDynWaves.compute
- docs/about/history.rst
- docs/user/ocean-simulation.rst
Since we have one for animated waves, it makes sense to have it for dynamic waves too. Had feedback that the depth cache was dampening wakes which was undesirable.
> Add Attenuation in Shallows setting to Dynamic Waves

- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- crest/Assets/Crest/Crest/Shaders/ShaderLibrary/UpdateShadow.hlsl
- docs/about/history.rst
Jittering shadow sampling causes shadows to bleed as a sample can land inside of geometry where it is shadowed. Easier to explain with screenshots:
You may notice there is still leaking, but that is only because the data being rendered is from the vertex shader which doesn't have enough density at that distance. Below is if the shadows are moved to the pixel shader (not part of this PR):
Adds about 0.04-0.05ms to the entire shadow sampling pass.
I have left the shadows rendered on the ocean surface on (from the vertex shader). Toggle "Create Sea Floor Depth Data" to see before and after.
> Fix shadow bleeding at shorelines

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
The LodData buffering breaks server builds currently as I forgot to test it. This is just a quick fix. It sets the OceanRenderer.BufferSize to 2 as a minimum. This value sets the shared buffered size like for cascade params and doesn't affect the buffered size for individual LodDataMgrs.
Also, if no sims requiring buffer count of two were enabled, exceptions would also be thrown as it assumed two as minimum.
Will make a proper fix. I have also added checking server/headless options to the release process to catch this in the future.
> Fix server builds and LodData* toggling

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Shaders/OceanConstants.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstner.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerGeometry.shader
- docs/about/history.rst
- docs/user/ocean-simulation.rst
- docs/user/shallows-and-shorelines.rst
One solution for #726.
Adds a maximum depth value for wave attenuation. Anything below this value will have no attenuation. Drawbacks is that wave attenuation is overall less effective. Moderate spectrums seem to work well enough. Completely optional as if the value is set to the maximum, the interpolation is skipped so this is a safe change.
TODO: documentation and release notes
> Optional maximum wave attenuation

- crest/Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Shaders/OceanGlobals.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstner.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerGeometry.shader
- docs/about/history.rst
Adds an offset as a global shader vector which the Gerster/FFT shader uses. It's not perfect but same tolerance as ShapeGerstnerBatched. The benefit of the global shader vector is no need to search for Shape* components.
> Fix floating origin for ShapeGerstner and ShapeFFT

- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/SimSettingsShadow.cs
- docs/about/history.rst
When the shadow simulation would hit an error it would disable itself and become unrecoverable - even in edit mode. This PR mainly addresses that but lead to a few other fixes and improvements:
- Failed state is now recoverable in edit mode without error spam
- Add "allow no shadows" option as disabling shadows on a light dynamically can be valid
- Fix shadow data not always clearing
- Fix "allow null light" from not working correctly
I've added an Error enum to prevent error spam which works well since errors are reported in order and one at a time.
> Fix shadow simulation error recovery

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
With this option, the _Water Body Override Material_ option can be used whilst still having an ocean. I made it _public_ as I believe people may want to script this.
> Add option for Ocean Renderer to ignore Water Body culling

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
- docs/user/water-bodies.rst
Calculates the overlapping area between water body and water tile to determine the best suited water body when using the material override feature. Makes this feature more predictable.
Before these changes, the water body which is first enabled would be chosen regardless of how significant the overlap was. This leaves the feature to the mercy of Unity's script execution order. And is quite confusing when toggling these components in the editor.
> Improve Water Body overlap when using Override Material

- crest/Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
For the varying water level feature, smoothing between the different levels was added. But it didn't take teleports into account.
So if I had the scene camera up very high above sea level and the game camera at sea level, and then entered play mode, the smoothing would be applied from the first frame. Or if I were to teleport from a beach to a lake at a higher elevation inland then, then it would also smooth which is not necessary.
This PR handles generic teleports with Floating Origin support. Since I don't know the best threshold, I exposed a property (_Teleport Threshold_) and set the default value to 10.
> Fix scale smoothing on height change on teleports

- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs.meta
- docs/about/history.rst
Make waterbody automatically clip-include
If clipping is enabled and clipping set to remove everything by default, then the waterbody ensures its area is clip-included.
This seems good to me, but needs the ocean lifetime stuff to ensure OnEnable is called after the OceanRenderer.
No urgency on this so ill just park it here.
NOTE: Just realised i created it against master instead of local-water-body. I'm guessing the life cycle stuff won't merge soon so this is probably fine, but review-by-commit is necessary, just the last one is relevant.
> Water body auto clip-include

- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- docs/about/history.rst
Reverts #928
I used Unity's memory profiler and saw a ballooned amount of RT memory usage. There were multiple instances of the same temporary RTs. I have gone back to using creating RTs manually :^(
Unity has not gotten back to me yet (been over a month). Unity's temporary RT pool has another strange bug, where temporary RTs would be bound to the wrong variable, which they have confirmed. This was preventing me from finishing underwater portals so will be able to finally finish it.
If you're wondering why I am using a static reference, it is because URP shares these APIs. The UR will hold the RTs which URP will use. This will reduce friction when merging and when reverting back to temporary RTS once bug is fixed.
> Fix underwater high memory

- crest/Assets/Crest/Crest/Scripts/Editor/BuildProcessor.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- crest/Assets/Crest/Crest/Shaders/Helpers/Resources.meta
- crest/Assets/Crest/Crest/Shaders/Helpers/Resources/Utility.shader
- crest/Assets/Crest/Crest/Shaders/Helpers/Resources/Utility.shader.meta
- crest/Assets/Crest/Crest/Shaders/Helpers/WaterVolume.hlsl
- crest/Assets/Crest/Crest/Shaders/Helpers/WaterVolume.hlsl.meta
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanConstants.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterEffect.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterMask.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/WaterVolumeGeometry.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/WaterVolumeGeometry.shader.meta
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffect.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectShared.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMaskHorizonShared.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMaskShared.hlsl
- docs/about/history.rst
- docs/user/underwater.rst
Adds a feature to render the underwater effect from a provided mesh. New options highlighted in yellow:
There are four modes:
- Full Screen: Same as before
- Geometry 2D: Only front face. Fog depth is to the far plane
- Geometry 3D: Front face and back face to create a volume of water
- Geometry Volume: As above but can fly through
For the _Geometry Volume_ option, the stencil buffer is used. It is a separate stencil buffer context so it will not interfere with the global stencil buffer.
Two global keywords have been used. But these are unlimited in 2022.
- Higher memory usage due to extra variants for ocean shader and extra passes for underwater. They are not stripped from builds so it is a new baseline cost **(1MB)**
- Every frame SetUpBoundary is called which is new cost but probably …
> Underwater from geometry

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanNormalMapping.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanShaderData.hlsl
- crest/Assets/Crest/Crest/Shaders/ShaderLibrary/Common.hlsl
- crest/Assets/Crest/Crest/Shaders/ShaderLibrary/Common.hlsl.meta
- crest/Assets/Crest/Crest/Shaders/ShaderLibrary/Texture.hlsl
- crest/Assets/Crest/Crest/Shaders/ShaderLibrary/Texture.hlsl.meta
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffect.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectShared.hlsl
Refactors our tiled (foam, caustics etc) texture usage.
Key points:
- creates a TiledTexture struct which holds all of the relevant data
- migrates from tex2D and friends to Texture2D
- will be further expanded in #951 which prompted this refactor
- uses namespaces (prompted by #943) and statics
I will be adding functions to the struct for handling floating origin. Not using a struct has become clunky.
As for namespaces, #943 means that our code is included in other people's shaders which could mean naming conflicts. We could just prefix everything but this is much nicer. It looks verbose right because I haven't added the namespace everywhere which would remove the need WaveHarmonic::Crest everywhere. Will do that in another PR.
A final note is that there is proxy methods for Sample and …
> Add TiledTexture shader struct

- crest/Assets/Crest/Crest/Shaders/Ocean.shader
Adds more debug visualisers for visualising the LOD data on the ocean surface. It also merges all of the visualiser options into one dropdown (highlighted in yellow).
> Add more debug visualisers

- crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
- docs/about/history.rst
Adds a scrollbar to the _Ocean Debug GUI_ when the _Draw LOD Datas Actual Size_ is used. Scrollbar is appears on the right and scrolls all LODs simultaneously.
> Add scrollbar to Ocean Debug GUI

- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- docs/about/history.rst
- docs/user/ocean-simulation.rst
Validation only allowed MeshRenderer to be used as an Ocean Input. Now anything deriving from Renderer (include particles) can be used. Also changes the behaviour of "disabled renderer" for trails and lines to only disable the rendering so the trails continue to update.
Foam and TrailRenderer go really well together.
The downside to this PR is that it could be a breaking change if someone has multiple renderers on the same GO. I've added a help box to the top of the component to inform the user of what renderer it is using.
Also, they aren't straightforward to use as the are quads so they need to be aligned the right way. But we have that issue with mesh renderer too.
> Allow any renderer as Ocean Input

- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- docs/about/history.rst
- docs/user/wave-conditions.rst
Based on discord discussions - bring ShapeGerstner back from the grave as it is useful for situations where a small number of highly controlled wave trains are required:
* Discrete shoreline wave trains
* Adding a few large wavelength "layout" waves that set the overall shape of the ocean
Also adds control over "reverse" waves so that pure trochoids can be produced if desired.
> ShapeGerstner revival

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFoam.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrPersistent.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsFoam.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateFoam.compute
- docs/about/history.rst
This prewarms the foam sim if it is the first step since being enabled or the first step for a teleport.
Currently foam can take a second or so to populate and the first moment has no foam. This PR mitigates that by prewarming the sim.
I worked out that swapping the `_SimDeltaTime` with `1.0 / _FoamFadeRate` will match the foam generated when the ocean is in a paused state in the editor (add a custom time provider and override time as zero or pause). So when entering play mode, it is seamless.
It's not the same as foam produced from running all the sims a few frames which would be the perfect solution, but that is probably costly for teleports.
Editor (ocean is at time zero)
First frame of play mode (current)
First frame of play mode (this PR)
> Prewarm foam sim on first frame and teleports

- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/EditorHelpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- docs/about/history.rst
- docs/user/faq.rst
- docs/user/underwater.rst
Adds optional (enabled by default) underwater rendering to scene and preview cameras.
I've implemented it in the simplest way without impacting the standalone player. I believe it will be even simpler for SRPs.
It has some drawbacks:
- RT reference is shared but the RTs aren't due to different RT requirements. So RTs are recreated every frame each view is open (not an issue for HDRP now or URP in 2022)
- Disabled underwater being disabled when high enough above surface in edit mode
- Disable fog extinction culling in edit mode
It seems reliable which is surprising as adding edit mode support normally introduces many issues and complexities.
> Underwater rendering in Edit Mode

- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
Before we were destroying/recreating which was wasteful. This PR avoids that by just calling Release.
> Reuse RT reference in Underwater Renderer

- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
- docs/about/history.rst
- docs/user/water-bodies.rst
Adds support for the water body material override. It grabs the material from one of the inner tiles. Seems to work well enough if we consider how it is used (WB should be far enough apart).
**EDIT:** Change the solution to something more accurate to the WB itself. Checking camera position is within the WB bounds in the UR. Other benefit is that it is code is contained within the UR which is nicer. Check the first commit to see original solution.
> Underwater Renderer support for Water Body material

- crest/Assets/Crest/Crest/Shaders/Resources/UpdateDynWaves.compute
- docs/about/history.rst
WIthout this fix, when scale is e.g. reduced, lod0 was getting populated with the previous lod0 data. This essentially dupes lod0 (lod0 data from previous frame ends up in both lod0 and lod1 in current frame), creating a pop and large displacement.
> For scale changes, pull in 0.0 values at cascade start/end

- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
- docs/about/history.rst
Unity doesn't set up lighting for us when using command buffers to draw things. When rendering the underwater effect, we were getting the last values which often will be the sun. But if there is another light which shines on a transparent object, and said transparent object is in view, then the last values will be from the ForwardAdd passes which is not the sun.
> Fix Underwater Renderer not using sun when other light shining on transparent object

- crest/Assets/Crest/Crest/Materials/OceanInputs/AlbedoColor.mat
- crest/Assets/Crest/Crest/Materials/OceanInputs/AlbedoColor.mat.meta
- crest/Assets/Crest/Crest/Scripts/BuildCommandBuffer.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAlbedoInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AlbedoColor.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AlbedoColor.shader.meta
- docs/about/history.rst
- docs/user/ocean-simulation.rst
I could not get particles to work with Albedo so I had to fix something and fixed a few other things:
- Albedo shader as most other shaders are multi-pass and we render all passes with DrawRenderer
- Render all sub-meshes so we can support particle trails
- Add a weird fix (Camera.SetupCurrent) to stop some things from flickering. I was given this by someone trying to get particles working for HDRP so looks like we need it anyway. Not sure what it does exactly but I think it sets up Camera.current.
Particles on surface in Demo scene.
This should work for SRPs too. But can always come back and modify or create another shader there.
> Fix non Mesh Renderer inputs and add Albedo shader

- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectShared.hlsl
- docs/about/history.rst
Fixes "Underwater Renderer > Filter Ocean Data" option not being applied to caustics. It was using slice index + 1, but the cascade data had the filter applied so by default it would be much higher.
> Fix "Underwater Renderer > Filter Ocean Data" not being applied to caustics

- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanShaderData.hlsl
- docs/about/history.rst
When shadow data is disabled the SS shadow texture was not set. This PR binds that texture to a white texture if disabled.
> Fix caustics no rendering if shadow data is disabled

- crest/Assets/Crest/Crest/Scripts/Editor/BuildProcessor.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanConstants.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanFoam.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanGlobals.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanLightingHelpers.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanShaderData.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanShaderHelpers.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/Resources/UnderwaterEffect.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffect.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectIncludes.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectIncludes.hlsl.meta
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectShared.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMaskHorizonShared.hlsl
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMaskShared.hlsl
_**Status:** Needs some work but ready for early feedback_
Adds an "includes" file for developers to add the underwater fog to their transparent shaders.
When the "Enable Shader API" option is enabled on the _Underwater Renderer_, it will:
- render the underwater effect before the transparent pass
- enable underwater rendering on ocean shader (like how it was before the underwater PP)
- populate global shader data (uses three global keywords)
Second point is unfortunate as it was nice not having underwater rendering in the ocean shader, but this allows users to keep their transparent objects rendered once in the transparent pass.
**Todo:**
The last one is a bit of a hassle now that most of the code is exposed. We can probably get away with not adding a Crest prefix to a few things like …
> Underwater Shader API

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Mask.cs
- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- docs/about/history.rst
Helps with #931 having underwater appear where it shouldn't due to self intersecting waves. This wasn't really a problem since the UR is disabled for above 2m and doesn't use the mask below -2m. I've added a release note for it anyway since the former could be disabled with a debug.
> Fix Underwater Renderer self intersecting waves in mask

- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- docs/about/history.rst
Weight was not being applied to reporting causing scale pop. Reported on Discord by scrappy.
> Fix ShapeFFT popping when enabled with zero weight

- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs
- docs/about/history.rst
If there is more than one ShapeFFT with different resolutions, the __Size_ will be wrong and cause FFT to speedup/jitter. Can also happen with only one ShapeFFT active at a time but one enabled after the other will overwrite it incorrectly.
> Fix FFT speed boosting when two or more are active in scene

- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- docs/about/history.rst
Removed from scripting as it would get stuck at zero. And the weight was being applied twice which is incorrect.
I was thinking of mentioning the latter as a breaking change but on second thought a slight behaviour change probably doesn't warrant it.
ShapeGerstnerBatched has the same problem but will leave it as deprecated and has CPU queries which I would have to apply the weight too.
> Fix ShapeGerstner weight not updating with _spectrumFixedAtRuntime

- crest/Assets/Crest/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/BoatProbes.cs
- crest/Assets/Crest/Crest/Scripts/Interaction/SimpleFloatingObject.cs
- docs/about/history.rst
Adds a _Maximum Buoyancy Force_ to clamp buoyancy.
Useful when buoyant objects are submerged a decent depth which can cause them to gain too much force and launch into the stratosphere.
By default, it is set to Infinity (ie no effect) so users will have to opt in.
> Maximum Buoyancy Force

- crest/Assets/Crest/Crest/Scripts/Editor/BuildProcessor.cs
- docs/about/history.rst
XR wasn't working for UR because keywords were being stripped as they have changed or keyword system has changed.
I've also brought file up-to-date with downstream.
> Fix UR XR in 2021.2 builds

- crest/Assets/Crest/Crest/Scripts/Editor/ObsoleteShaderGUI.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/DynWavesSphereWaterInteraction.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/DynWavesSphereWaterInteraction.shader.meta
- crest/Assets/Crest/Crest/Shaders/Resources/DynWavesSphereWaterInteraction.shader
- crest/Assets/Crest/Crest/Shaders/Resources/DynWavesSphereWaterInteraction.shader.meta
- docs/about/history.rst
Related #971 
We moved this shader into a Resources folder one level down and corrected the path for an include. But we forgot to add a dummy/stub shader in the original location which has caused a few upgrade issues.
This adds the dummy/stub shader to two locations and provides instructions on how users can fix it themselves.
I've added one to _Crest/Crest/Shaders/OceanInputs/_ and _Crest/Crest/Shaders/Resources_ since I was recommending people move it there before 4.15 was released.
> Give feedback instead of errors due to bad SWI shader move

- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/PropertyWrapper.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- crest/Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- docs/about/history.rst
Helps solve #999.
Fixes several leaks that will persist during an entire Unity session due to using [HideFlags.DontSave](https://docs.unity3d.com/ScriptReference/HideFlags.DontSave.html) or [HideFlags.HideAndDontSave](https://docs.unity3d.com/ScriptReference/HideFlags.HideAndDontSave.html).
> Fix leaks due to hide flags usage

- crest/Assets/Crest/Crest/Shaders/Helpers/Resources/Utility.shader
- docs/about/history.rst
I forgot to add XR things to the utility shader which broke stereo rendering.
> Fix XR SPI both eyes being the same

- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrPersistent.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTBaker.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs
- docs/about/history.rst
Helps solve #999.
These are leaks that happen during a single scene session as Unity will unload them on scene switch. But still nice to have them cleared. I have separated them into commits but can be reviewed as a whole.
> Fix texture leaks

- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- docs/about/history.rst
Fixes the last of #999
FFTCompute resources are not released so I am releasing/destroying resources when the last ShapeFFT is destroyed.
> Fix FFT leaks

- crest/Assets/Crest/Crest/Scripts/Editor/BuildProcessor.cs
- docs/about/history.rst
When no UR is present, shader stripping is skipped. The shader being in the Resources folder prevents Unity from stripping it.
> Fix long build times when underwater is not used

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
Related #630
Two cases of memory leaks have been fixed by Unity related to queries for a while now:
https://issuetracker.unity3d.com/issues/asyncgpureadback-can-leak-memory-under-certain-circumstances
https://issuetracker.unity3d.com/issues/asyncgpureadback-dot-request-never-releases-unused-allocated-memory
To be safe I have added a toggle for edit mode queries (enabled by default):
Re-enabling these is useful for visualising height queries and edit mode underwater rendering when height is modified.
> Re-enable height queries in edit mode

- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- docs/about/history.rst
I made baked depth cache point filtering which was a huge mistake... Switched to bilinear.
> Fix jagged shoreline foam when using baked depth cache

- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Shaders/Resources/FFT/FFTSpectrum.compute
- docs/about/history.rst
Now if you increase the resolution of the FFT, the waves will receive more samples, so the quality ramps with the FFT res. This is how it should have been all along, and it makes for a more natural implementation.
Increased FFT default res to 128 to help improve default quality. This is still cheaper than doing a single 512x512 FFT which would be standard in many systems.
I tried a few test scenes and it did not seem to break the results but a second pair of eyes might be useful.
Finally it adds validation to ensure the ShapeFFT behaves gracefully for invalid settings.
> Scale samples-per-wave with FFT res

- crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- docs/about/history.rst
Helps solve #999
Fixes more leaks. I went through to see if I could find more, but found none which were proper leaks where duplicates where made. There are still a few references which are not cleared on scene switch, but they were more involved/risky fixes to make and didn't seem worth it for a patch release since they were minor and non duplicating.
> Fix memory/reference leaks

- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.compute
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.shader
- docs/about/history.rst
Broken out from #1021 as this is simple and can be applied separately.
> Don't let flow period below 1s to avoid obvious phasing

- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- docs/about/history.rst
Expose option to double sample rate when generating final waves. This unfortunately requires higher res LOD data (1024 works well) because this effectively halves the range of detail and now at res=384 there is very little resolution left in the waves.
As previously, I'm finding higher LOD data resolution is required to get high quality results. To increase the default resolution, we'd likely need to break out LOD resolutions on a per-LOD basis as 1024x1024x8xTexelBytes x LodDataCount is a lot of video memory. For now i've added a tooltip that warns about this memory usage and labels the setting as preview.
Before [video](https://fr2ygz2xuzx8urqegqxn7uysnqr-my.sharepoint.com/:v:/g/personal/huw_bowles_waveharmonic_com/EScsHKPw375Aj1cClLx7ZJQB4vvtR-HGStAyczBSGThzNQ?e=MjWYkm)
After …
> Wave quality improvement

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrFlow.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
I accidentally had flow disabled when messing around with shoreline waves, so I added validation to the SWS for ocean Flow feature enabled on OR and on material.
Rather than duplicate that stuff, I factored out the validation code to a central location, which is in this PR.
This means I can call `OceanRenderer.ValidateFeatureEnabled` from the SWS validated editor.
I only did this for Flow as its the only one SWS. However i could roll out the minor change to `LodDataMgrFlow` to the other lod datas if you think it makes sense.
> Factor out feature validation so it can be used from SWS

- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
- crest/Assets/Development/Editor/AttributeValidator.cs
Allows for subclasses to filter enum options.
```c#
class BaseInput
{
[Filtered]
Mode _mode;
}
[FilterEnum("_mode", FilteredAttribute.Mode.Include, (int)Mode.Primitive, (int)Mode.Geometry)]
class Input {}
```
There is a demo commit with implementation on the inputs for testing if you wish.
It will have to be implemented in painted branch to avoid a merge conflict.
> Add enum filter attribute

- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateShadow.shader
- crest/Assets/Crest/Crest/Shaders/ShaderLibrary/UpdateShadow.hlsl
Unity's Blit has a lot of limitations like not supporting the RP tag. I have moved to using our own helper method which uses FST. This change will allow us to combine all RP subshaders into one file using the RP tag.
> Use full-screen triangle for shadow simulation

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrClipSurface.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsClipSurface.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
- docs/about/history.rst
Moved _Default Clipping State_ from _Ocean Renderer_ into _Sim Settings Clip Surface_ asset. I don't think a migration is worth the effort as we'd have to create a settings file if they don't have one which probably won't play nice in the migration pattern we favour.
> Move "default clipping state" to settings

- crest/Assets/Crest/Crest/Scripts/Editor/BuildProcessor.cs
- docs/about/history.rst
Fixes obsolete warnings seen on load / script recompile for using obsolete shader keyword API.
> Fix Build Processor obsolete warnings

- crest/Assets/Crest/Crest/Scripts/Constants.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- docs/about/history.rst
- docs/about/known-issues.rst
- docs/user/faq.rst
- docs/user/getting-started.rst
Crest doesn't support prefab mode but some components still run which causes problems. This makes disabling prefab mode more robust and expands the roster of components to all problematic components.
The prefab mode experience is that the OR from the scene will continue to run and be visible in prefab mode, but prefab mode changes will not be reflected in the scene view until it is saved. This is due to the OR in the scene view not knowing about the changes made in prefab mode as they are separate instances. This is the same for the other problematic components: UR, ShapeFFT and ShapeGerstner.
> Fix prefab mode breaking things

- crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Time/TimeProviderBase.cs
- crest/Assets/Crest/Crest/Scripts/Time/TimeProviderCustom.cs
- crest/Assets/Crest/Crest/Scripts/Time/TimeProviderCutscene.cs
- crest/Assets/Crest/Crest/Scripts/Time/TimeProviderDefault.cs
- crest/Assets/Crest/Crest/Scripts/Time/TimeProviderNetworked.cs
- docs/about/history.rst
Tripped over this while doing other changes - was not sure which DT to use. `DeltaTimeDynamics` seems to be completely unused, so removing.
> Remove unused DeltaTimeDynamics

- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/UserPainted/InputPainting.cs
Few minor tweaks after authoring Island waves.
Most significant is the wave direction change. When painting waves, take the direction the user is painting for the waves, don't incorporate the global wind heading offset. Adding the offset makes the behaviour very confusing and I don't envision a use case for this in practice.
> Tweaks to painting input

- crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
- docs/about/history.rst
After identifying potential issues with sorting, we decided picking sibling index as a sub-queue-index might work well.
So sorting of inputs effectively happens on two keys - primarily on queue index, and then secondarily on subqueue index, for which the sibling index can be used. So relative order of siblings will dictate order they apply, similar to Unity's UI system.
This took a bit of untangling to bring over from #1032. The queue value is not initialised for FFT/Gerstner, leaving that for #1032.
This simplifies/cleans up the code as a bonus.
> Helpers for register/deregister with input for subqueue index

- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Shaders/OceanHelpers.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGenerate.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerGeometry.shader
- crest/Assets/Crest/Crest/Shaders/Resources/FFT/FFTCompute.compute
- crest/Assets/Crest/Crest/Shaders/Resources/Gerstner.compute
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.compute
- crest/Assets/Crest/Crest/Shaders/Resources/ShapeCombine.shader
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateFoam.compute
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterMaskShared.hlsl
- docs/about/history.rst
Adds alpha blending for local waves (geometry or splines). It adds an _Additive_ option which is on by default. It can only be disabled for local waves as no point for global ones.
Also fixes FFTs writing into alpha channel which was adding a bunch of foam:
FFT Waves alpha channel rendered to the surface
Lastly, it removes variance from gerstner waves.
We don't use ShapeGerstner anywhere so example scenes shouldn't need tweaking.
I've added a test scene under Assets/Demo folder.
I'll look at reorganising the UI in another PR as it is getting cluttered.
> Local wave alpha blending

- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
Hides the "unset" value when not needed for filtered enums.
> Hide filtered enum unset value

- crest/Assets/Crest/Crest/Scripts/Helpers/Attributes/MultiPropertyAttribute.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/Editor/MultiPropertyDrawer.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/PredicatedFieldAttribute.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterHeightInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
Essentially cleans up UI for several components by hiding irrelevant sections per mode. Also includes a few fixes.
- Add hide option to Predicated
- Apply hide option to several components
- Add some extra headings
- Fix SFD input mode filter
I added the optional hide option as the last parameter which saved fixing up a bunch of stuff. Also _Predicated_ now keeps the disabled state so we can have multiple _Predicated_ attributes playing nicely together. Cannot do anything too fancy though.
> Add hide option to Predicated and clean up UI

- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- docs/about/history.rst
We were checking platform requirements during a build which we should not do.
> Fix spurious error during build process

- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Spline/SplinePoint.cs
- docs/about/history.rst
It was reported that splines had serious scalability issues in the editor.
No longer generate the spline mesh for each frame when it is not selected. And reduce spline mesh generation and draw spline gizmo calls significantly.
> Improve spline editor performance

- crest/Assets/Crest/Crest/Shaders/ShaderLibrary/Texture.hlsl
- docs/about/history.rst
PSSL has const correctness for functions. Fixes the following:
> Shader error in 'Crest/Ocean': Program 'Frag', member function 'Sample' not viable: 'this' argument has type 'WaveHarmonic::Crest::TiledTexture const', but function is not marked const at Crest/Crest/Shaders/OceanEmission.hlsl(129) (on ps5_cggc)
This appears to be PSSL only feature as the fix throws a compiler error elsewhere (comprehensive test not done). I tried putting const at the beginning of the function signature instead of the end which compiles but did not solve the problem on PSSL so must be different purpose.
> Fix PSSL compiler errors

- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- docs/about/history.rst
Fixes: #1056
Replaces: #1058 and #735
Makes the ocean tiles not pickable in the scene view. Rarely do developers need to pick the ocean from the scene view so there is no specific override, but will be disabled when ocean tiles are made visible through the appropriate debug option.
Unlike previous attempts, this uses the *HideAndDontSave* flag rather than the pickability API which has no downsides.
> Make ocean not pickable

- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
It is unnecessary as not having a viewpoint is harmless and valid in cases where the camera is created with a script. In those cases it would spam the logs which was a nuisance. We always use the main fallback so user intervention is not required.
> Remove viewpoint validation

- crest/Assets/Crest/Crest-Examples/Examples/Scripts/CustomPassForCamera.cs
- crest/Assets/Crest/Crest-Examples/Examples/Scripts/MaskFill.cs
- crest/Assets/Crest/Crest/Scripts/Collision/VisualiseCollisionArea.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/OceanDebugGUI.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAlbedoInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterDynWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterHeightInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/RegisterShadowInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Scripts/Spline/Spline.cs
- crest/Assets/Crest/Crest/Scripts/Spline/SplinePoint.cs
- crest/Assets/Crest/Crest/Scripts/Time/TimeProviderCutscene.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
- docs/about/history.rst
ExecuteAlways will also have scripts execute when building. This causes many issues. Executing when building is a side effect and there is no need for us to do so.
> Fix executing when building

- crest/Assets/Crest/Crest/Scripts/Helpers/Helpers.cs
- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
Gives control over various Mesh Renderer properties. We could add more fields to the Ocean Renderer for each property but other RPs (like HDRP) have a growing number of properties across versions.
> Add Water Tile Prefab field to Ocean Renderer

- crest/Assets/Crest/Crest-Examples/Main/Scenes/Internal/MainSceneCore.prefab
- crest/Assets/Crest/Crest/Scripts/Helpers/RenderAlphaOnSurface.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanValidation.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- docs/about/history.rst
Validate the layer if a renderer is present because if the _Water_ layer is excluded from any culling masks, then these may still execute without the _Ocean Renderer_ and thus without buffers being bound. This will cause a build failure and the error message is not helpful.
There is probably a proper fix other than validation but these renderers should really be on the same layer anyway.
> Validate Renderer Layer to prevent potential build failures

- crest/Assets/Crest/Crest/Scripts/Editor/BuildProcessor.cs
- crest/Assets/Crest/Crest/Scripts/Editor/Crest.Editor.asmdef
- crest/Packages/manifest.json
- docs/about/history.rst
If a user had ocean materials in either _Resources_ or _Addressables_, they would not be evaluated when stripping keywords from the underwater shader.
The stripping system is still not perfect and probably never will be. An alternative will need to be explored.
Thanks to Kospy for reporting and providing a solution for _Addressables_.
> Search Resources and Addressables when stripping underwater shader keywords

- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeWaves.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesSpectrum.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesSpectrum.shader.meta
- docs/about/history.rst
- docs/user/wave-conditions.rst
Adds support for mesh renderers to ShapeWaves. And adds a shader which samples the spectrum based on the painted data approach where RG channels are the XZ wave direction and together are the magnitude (0-1 maps to −1-1). Object rotation and _Wave Direction Heading Angle_ are also applied to the direction.
There is a demo scene under the Demo folder for testing. It samples waves using an arrow as a mask.
> Add wave sampling shader for renderer input

- crest/Assets/Crest/Crest/Scripts/Helpers/TextureArrayHelpers.cs
- crest/Assets/Crest/Crest/Scripts/Helpers/XRHelpers.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
XR SPI needs a texture array with two dimensions but was given a texture.
> Fix caustics not rendering in XR SPI when shadow simulation is disabled

- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- docs/about/history.rst
CBs on lights will run for all cameras so we need to restrict it to a single camera by adding and removing the CB using the camera events.
This broke XR spectator camera and could cause incorrect shadows in the simulation.
There is a possible Unity bug where the shadow input draw calls are duplicated and without any commands applied to them (including setting the render target).
> Fix shadow sim running for all cameras

- crest/Assets/Crest/Crest/Scripts/Helpers/XRHelpers.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.Effect.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- docs/about/history.rst
The _Underwater Renderer_ can now support multiple cameras including almost all of its features and optimisations. Exceptions are underwater culling and _Surface Self Intersection Fix Mode_. It is possible to support these too but would require some re-architecturing of the _Ocean Renderer_.
The current architecture is not ideal for multiple cameras, but was still possible and so worth doing. A re-architecture will improve things when a breaking change can be made.
Also no longer disable UR if fails validation in edit mode.
> Support multiple cameras for Underwater Renderer

- crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrDynWaves.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/DynWavesSphereWaterInteraction.shader
- docs/about/history.rst
Greatly improves performance when many SWI instances are in the scene. Without instancing, there would be one draw call per LOD per instance. Now there is only one draw call per LOD.
This has been implemented for SWI only as it is necessary for its scalability due to the nature of its usage often been as a composite and requiring several instances to achieve a desired shape.
For example, the "Spinner" example had 126 draw calls and now has only seven draw calls.
GPU instancing can only draw 1023 instances per draw, which should be more than enough, so for now the SWI also carries this limitation.
Another downside of instancing is that inputs cannot be sorted, but I do not believe there is a use case for that anyway.
Eventually moving towards compute shaders will replace this.
> Sphere Water Interaction GPU Instancing

- crest/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterRenderer.cs
- docs/about/history.rst
In certain cases memory would slowly increase indefinitely. It would be cleared when editor became active again but would like to avoid leaks altogether.
This could be a Unity bug but more effective to patch than report. It also has the benefit of saving energy.
> Do not execute in background

- crest/Assets/Crest/Crest-Examples/Whirlpool/Scripts/Whirlpool.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterHeightInput.cs
- docs/about/history.rst
Fixes renderer bounds thrashing in edit mode if using RegisterAnimWavesInput, RegisterHeightInput or Whirlpool.
There was a mismatch in reporting maximum displacement where the OR was clearing reported displacement in EditorApplication.update but these components were reporting in Update. Chunk renderer bounds are updated in Update so it would have alternating reported displacements which caused thrashing. It incurred a performance penalty and incorrect culling.
> Fix water renderer bounds thrashing in edit mode

- crest/Assets/Crest/Crest/Scripts/LodData/RegisterHeightInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs
- crest/Assets/Crest/Crest/Scripts/OceanChunkRenderer.cs
- crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/FFT/ShapeFFT.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstner.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerSplineHandling.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeWaves.cs
- docs/about/history.rst
This is a significant improvement to the displacement reporting mechanism which expands the water tile bounds to prevent culling. In many cases these were being expanded much larger than they needed to be.
Height is now reported separately and takes the minimum and maximum as it was additive before. Bounds also have an offset applied instead of expanding on both sides of the sea level to encompass varying heights.
Both height and displacement that come from a local input (renderer, spline, etc) are bounds tested against each water tile so that only the applicable inputs are included when reporting.
The end result is a significant improvement to culling of water tiles.
> Improve culling by reducing displacement over-reporting

- crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl
- docs/about/history.rst
Fixes #1040 
It is an issue with FXC so Unity cannot fix the problem. But they did provide the solution. Thank you.
> Fix Graphics API edge case causing rendering artefacts

- crest/Assets/Crest/Crest/Scripts/Interaction/SphereWaterInteraction.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgr.cs
- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs
- crest/Assets/Crest/Crest/Scripts/Shapes/ShapeWaves.cs
- crest/Assets/Crest/Crest/Scripts/WaterBody.cs
- docs/about/history.rst
Larger waves that are transitioning towards the end of the LOD chain were not having the blend pass applied to them, or not fully, due to the transition weight being passed into the blend pass. By parting the transition weight out, it can be excluded from the blend pass.
> Fix wave blending not applying to waves during transition towards the end of cascades

- crest/Assets/Crest/Crest/Scripts/LodData/RegisterAnimWavesInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFlowInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterFoamInput.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterLodDataInput.cs
- docs/about/history.rst
Some inputs will query displacements to counter water movement to stay in position. This was done in the Draw method which is called per LOD which was unnecessary. This significantly reduces queries.
> Reduce input displacement queries

- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/RegisterSeaFloorDepthInput.cs
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/CopyDepthIntoCache.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/OceanDepthsCache.shader
- docs/about/history.rst
If a baked depth cache is moved after baking, the depth will be incorrect. This solves that by making the depth relative to the transform. Now it can be moved providing the contents (terrain etc) are also moved with it.
To avoid breaking current depth caches, this is only applied to new ODCs or after hitting _Save cache to file_. There is an edge case which will break existing baked depth caches where a user swaps out a relative baked depth cache texture for a non relative one which can be solved by simply re-baking.
> Make Ocean Depth Cache depth relative

- crest/Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs
- crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs
- crest/Assets/Crest/Crest/Scripts/LodData/Settings/SimSettingsAnimatedWaves.cs
- crest/Assets/Crest/Crest/Shaders/Ocean.shader
- crest/Assets/Crest/Crest/Shaders/OceanConstants.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanHelpersNew.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/AnimWavesSpectrum.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/GerstnerShared.hlsl
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstner.shader
- crest/Assets/Crest/Crest/Shaders/OceanInputs/Resources/AnimWavesGerstnerGeometry.shader
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateDynWaves.compute
- crest/Assets/Crest/Crest/Shaders/Resources/UpdateFoam.compute
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterCurtain.shader
- crest/Assets/Crest/Crest/Shaders/Underwater/UnderwaterEffectShared.hlsl
Fixes incorrect depth values when away from zero, and greatly simplifies everything. Caution must be taken as infinity can cause issues.
Water depth sampling had to be moved to the fragment shader, as it had artifacts possibly from interpolation.
Additionally, improved fading out of shallow SSS towards the end of cascades.
> Fix #1156 Use infinity water depth
